"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _PUMP_STATUS:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PUMP_STATUSEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PUMP_STATUS.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PUMP_OFF: _PUMP_STATUS.ValueType  # 0
    PUMP_LOW: _PUMP_STATUS.ValueType  # 1
    PUMP_HIGH: _PUMP_STATUS.ValueType  # 2

class PUMP_STATUS(_PUMP_STATUS, metaclass=_PUMP_STATUSEnumTypeWrapper): ...

PUMP_OFF: PUMP_STATUS.ValueType  # 0
PUMP_LOW: PUMP_STATUS.ValueType  # 1
PUMP_HIGH: PUMP_STATUS.ValueType  # 2
Global___PUMP_STATUS: _TypeAlias = PUMP_STATUS  # noqa: Y015

class _BLOWER_STATUS:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _BLOWER_STATUSEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_BLOWER_STATUS.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    BLOWER_OFF: _BLOWER_STATUS.ValueType  # 0
    BLOWER_ON: _BLOWER_STATUS.ValueType  # 1

class BLOWER_STATUS(_BLOWER_STATUS, metaclass=_BLOWER_STATUSEnumTypeWrapper): ...

BLOWER_OFF: BLOWER_STATUS.ValueType  # 0
BLOWER_ON: BLOWER_STATUS.ValueType  # 1
Global___BLOWER_STATUS: _TypeAlias = BLOWER_STATUS  # noqa: Y015

class _HEAT_CHILLER_STATUS:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _HEAT_CHILLER_STATUSEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_HEAT_CHILLER_STATUS.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    HEAT_IDLE: _HEAT_CHILLER_STATUS.ValueType  # 0
    HEAT_WARMUP: _HEAT_CHILLER_STATUS.ValueType  # 1
    HEAT_HEATING: _HEAT_CHILLER_STATUS.ValueType  # 2
    HEAT_COOLDOWN: _HEAT_CHILLER_STATUS.ValueType  # 3
    CHILLING: _HEAT_CHILLER_STATUS.ValueType  # 4

class HEAT_CHILLER_STATUS(_HEAT_CHILLER_STATUS, metaclass=_HEAT_CHILLER_STATUSEnumTypeWrapper): ...

HEAT_IDLE: HEAT_CHILLER_STATUS.ValueType  # 0
HEAT_WARMUP: HEAT_CHILLER_STATUS.ValueType  # 1
HEAT_HEATING: HEAT_CHILLER_STATUS.ValueType  # 2
HEAT_COOLDOWN: HEAT_CHILLER_STATUS.ValueType  # 3
CHILLING: HEAT_CHILLER_STATUS.ValueType  # 4
Global___HEAT_CHILLER_STATUS: _TypeAlias = HEAT_CHILLER_STATUS  # noqa: Y015

class _FILTER_STATUS:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _FILTER_STATUSEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_FILTER_STATUS.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    FILTER_IDLE: _FILTER_STATUS.ValueType  # 0
    FILTER_PURGE: _FILTER_STATUS.ValueType  # 1
    FILTER_FILTERING: _FILTER_STATUS.ValueType  # 2
    FILTER_SUSPENDED: _FILTER_STATUS.ValueType  # 3
    FILTER_BOOST: _FILTER_STATUS.ValueType  # 4

class FILTER_STATUS(_FILTER_STATUS, metaclass=_FILTER_STATUSEnumTypeWrapper): ...

FILTER_IDLE: FILTER_STATUS.ValueType  # 0
FILTER_PURGE: FILTER_STATUS.ValueType  # 1
FILTER_FILTERING: FILTER_STATUS.ValueType  # 2
FILTER_SUSPENDED: FILTER_STATUS.ValueType  # 3
FILTER_BOOST: FILTER_STATUS.ValueType  # 4
Global___FILTER_STATUS: _TypeAlias = FILTER_STATUS  # noqa: Y015

class _OZONE_STATUS:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _OZONE_STATUSEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_OZONE_STATUS.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    OZONE_IDLE: _OZONE_STATUS.ValueType  # 0
    OZONE_ACTIVE: _OZONE_STATUS.ValueType  # 1
    OZONE_SUSPENDED: _OZONE_STATUS.ValueType  # 2

class OZONE_STATUS(_OZONE_STATUS, metaclass=_OZONE_STATUSEnumTypeWrapper): ...

OZONE_IDLE: OZONE_STATUS.ValueType  # 0
OZONE_ACTIVE: OZONE_STATUS.ValueType  # 1
OZONE_SUSPENDED: OZONE_STATUS.ValueType  # 2
Global___OZONE_STATUS: _TypeAlias = OZONE_STATUS  # noqa: Y015

class _ONZEN_STATUS:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ONZEN_STATUSEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ONZEN_STATUS.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ONZEN_IDLE: _ONZEN_STATUS.ValueType  # 0
    ONZEN_ACTIVE: _ONZEN_STATUS.ValueType  # 1
    ONZEN_SUSPENDED: _ONZEN_STATUS.ValueType  # 2

class ONZEN_STATUS(_ONZEN_STATUS, metaclass=_ONZEN_STATUSEnumTypeWrapper): ...

ONZEN_IDLE: ONZEN_STATUS.ValueType  # 0
ONZEN_ACTIVE: ONZEN_STATUS.ValueType  # 1
ONZEN_SUSPENDED: ONZEN_STATUS.ValueType  # 2
Global___ONZEN_STATUS: _TypeAlias = ONZEN_STATUS  # noqa: Y015

class _PRODUCT_CODES:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PRODUCT_CODESEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PRODUCT_CODES.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SPA_NA_COLDFIRE: _PRODUCT_CODES.ValueType  # 65536
    SPA_EURO_COLDFIRE: _PRODUCT_CODES.ValueType  # 65537
    SPA_NA_LPC: _PRODUCT_CODES.ValueType  # 65538
    SPA_EURO_LPC: _PRODUCT_CODES.ValueType  # 65539
    SAUNA_COLDFIRE: _PRODUCT_CODES.ValueType  # 131072
    SAUNA_LPC: _PRODUCT_CODES.ValueType  # 131073
    COLD_TUB_COLDFIRE: _PRODUCT_CODES.ValueType  # 196608
    COLD_TUB_LPC: _PRODUCT_CODES.ValueType  # 196609
    PERIPHERAL_WAU: _PRODUCT_CODES.ValueType  # 262144
    PERIPHERAL_ONZEN: _PRODUCT_CODES.ValueType  # 262145
    PERIPHERAL_TOP_SIDE_A10: _PRODUCT_CODES.ValueType  # 262146

class PRODUCT_CODES(_PRODUCT_CODES, metaclass=_PRODUCT_CODESEnumTypeWrapper): ...

SPA_NA_COLDFIRE: PRODUCT_CODES.ValueType  # 65536
SPA_EURO_COLDFIRE: PRODUCT_CODES.ValueType  # 65537
SPA_NA_LPC: PRODUCT_CODES.ValueType  # 65538
SPA_EURO_LPC: PRODUCT_CODES.ValueType  # 65539
SAUNA_COLDFIRE: PRODUCT_CODES.ValueType  # 131072
SAUNA_LPC: PRODUCT_CODES.ValueType  # 131073
COLD_TUB_COLDFIRE: PRODUCT_CODES.ValueType  # 196608
COLD_TUB_LPC: PRODUCT_CODES.ValueType  # 196609
PERIPHERAL_WAU: PRODUCT_CODES.ValueType  # 262144
PERIPHERAL_ONZEN: PRODUCT_CODES.ValueType  # 262145
PERIPHERAL_TOP_SIDE_A10: PRODUCT_CODES.ValueType  # 262146
Global___PRODUCT_CODES: _TypeAlias = PRODUCT_CODES  # noqa: Y015

class _ARCTIC_BRAND:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ARCTIC_BRANDEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ARCTIC_BRAND.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ARCTIC: _ARCTIC_BRAND.ValueType  # 0
    COYOTE: _ARCTIC_BRAND.ValueType  # 1
    APOLLO: _ARCTIC_BRAND.ValueType  # 2
    COLDTUB: _ARCTIC_BRAND.ValueType  # 3

class ARCTIC_BRAND(_ARCTIC_BRAND, metaclass=_ARCTIC_BRANDEnumTypeWrapper): ...

ARCTIC: ARCTIC_BRAND.ValueType  # 0
COYOTE: ARCTIC_BRAND.ValueType  # 1
APOLLO: ARCTIC_BRAND.ValueType  # 2
COLDTUB: ARCTIC_BRAND.ValueType  # 3
Global___ARCTIC_BRAND: _TypeAlias = ARCTIC_BRAND  # noqa: Y015

class _SPEED:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SPEEDEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SPEED.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SPEED_GONE: _SPEED.ValueType  # 0
    SPEED_ONE: _SPEED.ValueType  # 1
    SPEED_TWO: _SPEED.ValueType  # 2

class SPEED(_SPEED, metaclass=_SPEEDEnumTypeWrapper): ...

SPEED_GONE: SPEED.ValueType  # 0
SPEED_ONE: SPEED.ValueType  # 1
SPEED_TWO: SPEED.ValueType  # 2
Global___SPEED: _TypeAlias = SPEED  # noqa: Y015

class _PHASE:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PHASEEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PHASE.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PHASE_TRUE_THREE: _PHASE.ValueType  # 0
    PHASE_SINGLE: _PHASE.ValueType  # 1
    PHASE_TWO: _PHASE.ValueType  # 2
    PHASE_THREE: _PHASE.ValueType  # 3

class PHASE(_PHASE, metaclass=_PHASEEnumTypeWrapper): ...

PHASE_TRUE_THREE: PHASE.ValueType  # 0
PHASE_SINGLE: PHASE.ValueType  # 1
PHASE_TWO: PHASE.ValueType  # 2
PHASE_THREE: PHASE.ValueType  # 3
Global___PHASE: _TypeAlias = PHASE  # noqa: Y015

class _TEMPERATURE_UNIT:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _TEMPERATURE_UNITEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_TEMPERATURE_UNIT.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    FAHRENHEIT: _TEMPERATURE_UNIT.ValueType  # 0
    CELSIUS: _TEMPERATURE_UNIT.ValueType  # 1

class TEMPERATURE_UNIT(_TEMPERATURE_UNIT, metaclass=_TEMPERATURE_UNITEnumTypeWrapper): ...

FAHRENHEIT: TEMPERATURE_UNIT.ValueType  # 0
CELSIUS: TEMPERATURE_UNIT.ValueType  # 1
Global___TEMPERATURE_UNIT: _TypeAlias = TEMPERATURE_UNIT  # noqa: Y015

class _LIGHTS_EFFECT:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _LIGHTS_EFFECTEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_LIGHTS_EFFECT.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    LIGHTS_EFFECT_NONE: _LIGHTS_EFFECT.ValueType  # 0
    LIGHTS_EFFECT_FADE: _LIGHTS_EFFECT.ValueType  # 1
    LIGHTS_EFFECT_SCROLL: _LIGHTS_EFFECT.ValueType  # 2
    LIGHTS_EFFECT_STROBE: _LIGHTS_EFFECT.ValueType  # 3

class LIGHTS_EFFECT(_LIGHTS_EFFECT, metaclass=_LIGHTS_EFFECTEnumTypeWrapper): ...

LIGHTS_EFFECT_NONE: LIGHTS_EFFECT.ValueType  # 0
LIGHTS_EFFECT_FADE: LIGHTS_EFFECT.ValueType  # 1
LIGHTS_EFFECT_SCROLL: LIGHTS_EFFECT.ValueType  # 2
LIGHTS_EFFECT_STROBE: LIGHTS_EFFECT.ValueType  # 3
Global___LIGHTS_EFFECT: _TypeAlias = LIGHTS_EFFECT  # noqa: Y015

class _SCHEDULE_TYPE:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SCHEDULE_TYPEEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SCHEDULE_TYPE.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    OZONE: _SCHEDULE_TYPE.ValueType  # 0
    FILTRATION: _SCHEDULE_TYPE.ValueType  # 1
    ONZEN: _SCHEDULE_TYPE.ValueType  # 2
    OFF_PEAK: _SCHEDULE_TYPE.ValueType  # 3
    MID_PEAK: _SCHEDULE_TYPE.ValueType  # 4
    PEAK: _SCHEDULE_TYPE.ValueType  # 5

class SCHEDULE_TYPE(_SCHEDULE_TYPE, metaclass=_SCHEDULE_TYPEEnumTypeWrapper): ...

OZONE: SCHEDULE_TYPE.ValueType  # 0
FILTRATION: SCHEDULE_TYPE.ValueType  # 1
ONZEN: SCHEDULE_TYPE.ValueType  # 2
OFF_PEAK: SCHEDULE_TYPE.ValueType  # 3
MID_PEAK: SCHEDULE_TYPE.ValueType  # 4
PEAK: SCHEDULE_TYPE.ValueType  # 5
Global___SCHEDULE_TYPE: _TypeAlias = SCHEDULE_TYPE  # noqa: Y015

class _ERROR_CODE:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ERROR_CODEEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ERROR_CODE.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ERROR_CODE_NONE: _ERROR_CODE.ValueType  # 0
    NO_FLOW: _ERROR_CODE.ValueType  # 1
    FLOW_SWITCH: _ERROR_CODE.ValueType  # 2
    WATER_OVER_TEMP: _ERROR_CODE.ValueType  # 3
    WATER_TEMP_PROBE: _ERROR_CODE.ValueType  # 4
    HEATER_HIGH_LIMIT: _ERROR_CODE.ValueType  # 5
    HEATER_OVER_TEMP: _ERROR_CODE.ValueType  # 6
    HEATER_TEMP_PROBE: _ERROR_CODE.ValueType  # 7
    FLOW_OVER_TEMP: _ERROR_CODE.ValueType  # 8
    FLOW_TEMP_PROBE: _ERROR_CODE.ValueType  # 9
    RELAY_K1_DAMAGED: _ERROR_CODE.ValueType  # 10
    RELAY_K2_DAMAGED: _ERROR_CODE.ValueType  # 11
    RELAY_K3_DAMAGED: _ERROR_CODE.ValueType  # 12
    RELAY_K4_DAMAGED: _ERROR_CODE.ValueType  # 13
    RELAY_K5_DAMAGED: _ERROR_CODE.ValueType  # 14
    RELAY_K6_DAMAGED: _ERROR_CODE.ValueType  # 15
    RELAY_K7_DAMAGED: _ERROR_CODE.ValueType  # 16
    RELAY_K8_DAMAGED: _ERROR_CODE.ValueType  # 17
    RELAY_K9_DAMAGED: _ERROR_CODE.ValueType  # 18
    RELAY_K10_DAMAGED: _ERROR_CODE.ValueType  # 19
    RELAY_K11_DAMAGED: _ERROR_CODE.ValueType  # 20
    RELAY_K12_DAMAGED: _ERROR_CODE.ValueType  # 21
    RELAY_K13_DAMAGED: _ERROR_CODE.ValueType  # 22
    RELAY_K14_DAMAGED: _ERROR_CODE.ValueType  # 23
    RELAY_K15_16_DAMAGED: _ERROR_CODE.ValueType  # 24
    RELAY_K17_DAMAGED: _ERROR_CODE.ValueType  # 25
    PUMP_1_LOW_FUSE_BLOWN: _ERROR_CODE.ValueType  # 26
    PUMP_1_HIGH_FUSE_BLOWN: _ERROR_CODE.ValueType  # 27
    PUMP_2_FUSE_BLOWN: _ERROR_CODE.ValueType  # 28
    PUMP_3_FUSE_BLOWN: _ERROR_CODE.ValueType  # 29
    PUMP_4_FUSE_BLOWN: _ERROR_CODE.ValueType  # 30
    PUMP_5_FUSE_BLOWN: _ERROR_CODE.ValueType  # 31
    BLOWER_1_FUSE_BLOWN: _ERROR_CODE.ValueType  # 32
    BLOWER_2_FUSE_BLOWN: _ERROR_CODE.ValueType  # 33
    HEATER_FUSE_BLOWN: _ERROR_CODE.ValueType  # 34
    PUMP_1_LOW_OVERCURRENT: _ERROR_CODE.ValueType  # 35
    PUMP_1_HIGH_OVERCURRENT: _ERROR_CODE.ValueType  # 36
    PUMP_2_OVERCURRENT: _ERROR_CODE.ValueType  # 37
    PUMP_3_OVERCURRENT: _ERROR_CODE.ValueType  # 38
    PUMP_4_OVERCURRENT: _ERROR_CODE.ValueType  # 39
    PUMP_5_OVERCURRENT: _ERROR_CODE.ValueType  # 40
    BLOWER_1_OVERCURRENT: _ERROR_CODE.ValueType  # 41
    BLOWER_2_OVERCURRENT: _ERROR_CODE.ValueType  # 42
    HEATER_OVERCURRENT: _ERROR_CODE.ValueType  # 43
    PUMP_HEATER_RUNNING: _ERROR_CODE.ValueType  # 65536
    PUMP_NOT_CONFIGURED: _ERROR_CODE.ValueType  # 65537
    PUMP_RELAY_DISABLED: _ERROR_CODE.ValueType  # 65538
    PUMP_EXCEEDS_BREAKER: _ERROR_CODE.ValueType  # 65539
    BLOWER_NOT_CONFIGURED: _ERROR_CODE.ValueType  # 65540
    BLOWER_RELAY_DISABLED: _ERROR_CODE.ValueType  # 65541
    BLOWER_EXCEED_BREAKER: _ERROR_CODE.ValueType  # 65542
    HEATER_DISABLED_PEAK: _ERROR_CODE.ValueType  # 65543
    FILTER_DISABLED_PEAK: _ERROR_CODE.ValueType  # 65544
    OZONE_DISABLED_PEAK: _ERROR_CODE.ValueType  # 65545
    ONZEN_DISABLED_PEAK: _ERROR_CODE.ValueType  # 65546
    HEATER_DISABLED_MIDPEAK: _ERROR_CODE.ValueType  # 65547
    FILTER_DISABLED_MIDPEAK: _ERROR_CODE.ValueType  # 65548
    OZONE_DISABLED_MIDPEAK: _ERROR_CODE.ValueType  # 65549
    ONZEN_DISABLED_MIDPEAK: _ERROR_CODE.ValueType  # 65550
    PH_HIGH: _ERROR_CODE.ValueType  # 65551
    HEATER_PROBE_DISCONNECTED: _ERROR_CODE.ValueType  # 65552

class ERROR_CODE(_ERROR_CODE, metaclass=_ERROR_CODEEnumTypeWrapper): ...

ERROR_CODE_NONE: ERROR_CODE.ValueType  # 0
NO_FLOW: ERROR_CODE.ValueType  # 1
FLOW_SWITCH: ERROR_CODE.ValueType  # 2
WATER_OVER_TEMP: ERROR_CODE.ValueType  # 3
WATER_TEMP_PROBE: ERROR_CODE.ValueType  # 4
HEATER_HIGH_LIMIT: ERROR_CODE.ValueType  # 5
HEATER_OVER_TEMP: ERROR_CODE.ValueType  # 6
HEATER_TEMP_PROBE: ERROR_CODE.ValueType  # 7
FLOW_OVER_TEMP: ERROR_CODE.ValueType  # 8
FLOW_TEMP_PROBE: ERROR_CODE.ValueType  # 9
RELAY_K1_DAMAGED: ERROR_CODE.ValueType  # 10
RELAY_K2_DAMAGED: ERROR_CODE.ValueType  # 11
RELAY_K3_DAMAGED: ERROR_CODE.ValueType  # 12
RELAY_K4_DAMAGED: ERROR_CODE.ValueType  # 13
RELAY_K5_DAMAGED: ERROR_CODE.ValueType  # 14
RELAY_K6_DAMAGED: ERROR_CODE.ValueType  # 15
RELAY_K7_DAMAGED: ERROR_CODE.ValueType  # 16
RELAY_K8_DAMAGED: ERROR_CODE.ValueType  # 17
RELAY_K9_DAMAGED: ERROR_CODE.ValueType  # 18
RELAY_K10_DAMAGED: ERROR_CODE.ValueType  # 19
RELAY_K11_DAMAGED: ERROR_CODE.ValueType  # 20
RELAY_K12_DAMAGED: ERROR_CODE.ValueType  # 21
RELAY_K13_DAMAGED: ERROR_CODE.ValueType  # 22
RELAY_K14_DAMAGED: ERROR_CODE.ValueType  # 23
RELAY_K15_16_DAMAGED: ERROR_CODE.ValueType  # 24
RELAY_K17_DAMAGED: ERROR_CODE.ValueType  # 25
PUMP_1_LOW_FUSE_BLOWN: ERROR_CODE.ValueType  # 26
PUMP_1_HIGH_FUSE_BLOWN: ERROR_CODE.ValueType  # 27
PUMP_2_FUSE_BLOWN: ERROR_CODE.ValueType  # 28
PUMP_3_FUSE_BLOWN: ERROR_CODE.ValueType  # 29
PUMP_4_FUSE_BLOWN: ERROR_CODE.ValueType  # 30
PUMP_5_FUSE_BLOWN: ERROR_CODE.ValueType  # 31
BLOWER_1_FUSE_BLOWN: ERROR_CODE.ValueType  # 32
BLOWER_2_FUSE_BLOWN: ERROR_CODE.ValueType  # 33
HEATER_FUSE_BLOWN: ERROR_CODE.ValueType  # 34
PUMP_1_LOW_OVERCURRENT: ERROR_CODE.ValueType  # 35
PUMP_1_HIGH_OVERCURRENT: ERROR_CODE.ValueType  # 36
PUMP_2_OVERCURRENT: ERROR_CODE.ValueType  # 37
PUMP_3_OVERCURRENT: ERROR_CODE.ValueType  # 38
PUMP_4_OVERCURRENT: ERROR_CODE.ValueType  # 39
PUMP_5_OVERCURRENT: ERROR_CODE.ValueType  # 40
BLOWER_1_OVERCURRENT: ERROR_CODE.ValueType  # 41
BLOWER_2_OVERCURRENT: ERROR_CODE.ValueType  # 42
HEATER_OVERCURRENT: ERROR_CODE.ValueType  # 43
PUMP_HEATER_RUNNING: ERROR_CODE.ValueType  # 65536
PUMP_NOT_CONFIGURED: ERROR_CODE.ValueType  # 65537
PUMP_RELAY_DISABLED: ERROR_CODE.ValueType  # 65538
PUMP_EXCEEDS_BREAKER: ERROR_CODE.ValueType  # 65539
BLOWER_NOT_CONFIGURED: ERROR_CODE.ValueType  # 65540
BLOWER_RELAY_DISABLED: ERROR_CODE.ValueType  # 65541
BLOWER_EXCEED_BREAKER: ERROR_CODE.ValueType  # 65542
HEATER_DISABLED_PEAK: ERROR_CODE.ValueType  # 65543
FILTER_DISABLED_PEAK: ERROR_CODE.ValueType  # 65544
OZONE_DISABLED_PEAK: ERROR_CODE.ValueType  # 65545
ONZEN_DISABLED_PEAK: ERROR_CODE.ValueType  # 65546
HEATER_DISABLED_MIDPEAK: ERROR_CODE.ValueType  # 65547
FILTER_DISABLED_MIDPEAK: ERROR_CODE.ValueType  # 65548
OZONE_DISABLED_MIDPEAK: ERROR_CODE.ValueType  # 65549
ONZEN_DISABLED_MIDPEAK: ERROR_CODE.ValueType  # 65550
PH_HIGH: ERROR_CODE.ValueType  # 65551
HEATER_PROBE_DISCONNECTED: ERROR_CODE.ValueType  # 65552
Global___ERROR_CODE: _TypeAlias = ERROR_CODE  # noqa: Y015

class _RELAY_ENUM:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _RELAY_ENUMEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_RELAY_ENUM.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    RELAY_K1: _RELAY_ENUM.ValueType  # 0
    RELAY_K2: _RELAY_ENUM.ValueType  # 1
    RELAY_K3: _RELAY_ENUM.ValueType  # 2
    RELAY_K4: _RELAY_ENUM.ValueType  # 3
    RELAY_K5: _RELAY_ENUM.ValueType  # 4
    RELAY_K6: _RELAY_ENUM.ValueType  # 5
    RELAY_K7: _RELAY_ENUM.ValueType  # 6
    RELAY_K8: _RELAY_ENUM.ValueType  # 7
    RELAY_K9: _RELAY_ENUM.ValueType  # 8
    RELAY_K10: _RELAY_ENUM.ValueType  # 9
    RELAY_K14: _RELAY_ENUM.ValueType  # 10
    RELAY_K17: _RELAY_ENUM.ValueType  # 11
    RELAY_DEFAULT: _RELAY_ENUM.ValueType  # 12

class RELAY_ENUM(_RELAY_ENUM, metaclass=_RELAY_ENUMEnumTypeWrapper): ...

RELAY_K1: RELAY_ENUM.ValueType  # 0
RELAY_K2: RELAY_ENUM.ValueType  # 1
RELAY_K3: RELAY_ENUM.ValueType  # 2
RELAY_K4: RELAY_ENUM.ValueType  # 3
RELAY_K5: RELAY_ENUM.ValueType  # 4
RELAY_K6: RELAY_ENUM.ValueType  # 5
RELAY_K7: RELAY_ENUM.ValueType  # 6
RELAY_K8: RELAY_ENUM.ValueType  # 7
RELAY_K9: RELAY_ENUM.ValueType  # 8
RELAY_K10: RELAY_ENUM.ValueType  # 9
RELAY_K14: RELAY_ENUM.ValueType  # 10
RELAY_K17: RELAY_ENUM.ValueType  # 11
RELAY_DEFAULT: RELAY_ENUM.ValueType  # 12
Global___RELAY_ENUM: _TypeAlias = RELAY_ENUM  # noqa: Y015

class _DEVICE_ENUM:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _DEVICE_ENUMEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_DEVICE_ENUM.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DEVICE_PUMP1: _DEVICE_ENUM.ValueType  # 0
    DEVICE_PUMP2: _DEVICE_ENUM.ValueType  # 1
    DEVICE_PUMP3: _DEVICE_ENUM.ValueType  # 2
    DEVICE_PUMP4: _DEVICE_ENUM.ValueType  # 3
    DEVICE_PUMP5: _DEVICE_ENUM.ValueType  # 4
    DEVICE_BLOWER1: _DEVICE_ENUM.ValueType  # 5
    DEVICE_BLOWER2: _DEVICE_ENUM.ValueType  # 6
    DEVICE_HEATER: _DEVICE_ENUM.ValueType  # 7
    DEVICE_OZONE1: _DEVICE_ENUM.ValueType  # 8
    DEVICE_OZONE2: _DEVICE_ENUM.ValueType  # 9
    DEVICE_ONZEN: _DEVICE_ENUM.ValueType  # 10
    DEVICE_FAN: _DEVICE_ENUM.ValueType  # 11
    DEVICE_LAST: _DEVICE_ENUM.ValueType  # 12

class DEVICE_ENUM(_DEVICE_ENUM, metaclass=_DEVICE_ENUMEnumTypeWrapper): ...

DEVICE_PUMP1: DEVICE_ENUM.ValueType  # 0
DEVICE_PUMP2: DEVICE_ENUM.ValueType  # 1
DEVICE_PUMP3: DEVICE_ENUM.ValueType  # 2
DEVICE_PUMP4: DEVICE_ENUM.ValueType  # 3
DEVICE_PUMP5: DEVICE_ENUM.ValueType  # 4
DEVICE_BLOWER1: DEVICE_ENUM.ValueType  # 5
DEVICE_BLOWER2: DEVICE_ENUM.ValueType  # 6
DEVICE_HEATER: DEVICE_ENUM.ValueType  # 7
DEVICE_OZONE1: DEVICE_ENUM.ValueType  # 8
DEVICE_OZONE2: DEVICE_ENUM.ValueType  # 9
DEVICE_ONZEN: DEVICE_ENUM.ValueType  # 10
DEVICE_FAN: DEVICE_ENUM.ValueType  # 11
DEVICE_LAST: DEVICE_ENUM.ValueType  # 12
Global___DEVICE_ENUM: _TypeAlias = DEVICE_ENUM  # noqa: Y015

@_typing.final
class lpc_live(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TEMPERATURE_FIELD_NUMBER: _builtins.int
    PUMP_1_FIELD_NUMBER: _builtins.int
    PUMP_2_FIELD_NUMBER: _builtins.int
    PUMP_3_FIELD_NUMBER: _builtins.int
    PUMP_4_FIELD_NUMBER: _builtins.int
    PUMP_5_FIELD_NUMBER: _builtins.int
    BLOWER_1_FIELD_NUMBER: _builtins.int
    BLOWER_2_FIELD_NUMBER: _builtins.int
    EXHAUST_FAN_FIELD_NUMBER: _builtins.int
    AUDIO_FIELD_NUMBER: _builtins.int
    LIGHTS_FIELD_NUMBER: _builtins.int
    STAND_BY_FIELD_NUMBER: _builtins.int
    HEATER_FIELD_NUMBER: _builtins.int
    FILTER_FIELD_NUMBER: _builtins.int
    OZONE_FIELD_NUMBER: _builtins.int
    ONZEN_FIELD_NUMBER: _builtins.int
    FREEZE_PROTECT_FIELD_NUMBER: _builtins.int
    ECONO_HEATER_DISABLED_FIELD_NUMBER: _builtins.int
    ECONO_FILTER_DISABLED_FIELD_NUMBER: _builtins.int
    ECONO_OZONE_DISABLED_FIELD_NUMBER: _builtins.int
    ECONO_ONZEN_DISABLED_FIELD_NUMBER: _builtins.int
    LIGHTS2_FIELD_NUMBER: _builtins.int
    temperature: _builtins.int
    pump_1: Global___PUMP_STATUS.ValueType
    pump_2: Global___PUMP_STATUS.ValueType
    pump_3: Global___PUMP_STATUS.ValueType
    pump_4: Global___PUMP_STATUS.ValueType
    pump_5: Global___PUMP_STATUS.ValueType
    blower_1: Global___BLOWER_STATUS.ValueType
    blower_2: Global___BLOWER_STATUS.ValueType
    exhaust_fan: _builtins.bool
    audio: _builtins.bool
    lights: _builtins.bool
    stand_by: _builtins.bool
    heater: Global___HEAT_CHILLER_STATUS.ValueType
    filter: Global___FILTER_STATUS.ValueType
    ozone: Global___OZONE_STATUS.ValueType
    onzen: Global___ONZEN_STATUS.ValueType
    freeze_protect: _builtins.bool
    econo_heater_disabled: _builtins.bool
    econo_filter_disabled: _builtins.bool
    econo_ozone_disabled: _builtins.bool
    econo_onzen_disabled: _builtins.bool
    lights2: _builtins.bool
    def __init__(
        self,
        *,
        temperature: _builtins.int | None = ...,
        pump_1: Global___PUMP_STATUS.ValueType | None = ...,
        pump_2: Global___PUMP_STATUS.ValueType | None = ...,
        pump_3: Global___PUMP_STATUS.ValueType | None = ...,
        pump_4: Global___PUMP_STATUS.ValueType | None = ...,
        pump_5: Global___PUMP_STATUS.ValueType | None = ...,
        blower_1: Global___BLOWER_STATUS.ValueType | None = ...,
        blower_2: Global___BLOWER_STATUS.ValueType | None = ...,
        exhaust_fan: _builtins.bool | None = ...,
        audio: _builtins.bool | None = ...,
        lights: _builtins.bool | None = ...,
        stand_by: _builtins.bool | None = ...,
        heater: Global___HEAT_CHILLER_STATUS.ValueType | None = ...,
        filter: Global___FILTER_STATUS.ValueType | None = ...,
        ozone: Global___OZONE_STATUS.ValueType | None = ...,
        onzen: Global___ONZEN_STATUS.ValueType | None = ...,
        freeze_protect: _builtins.bool | None = ...,
        econo_heater_disabled: _builtins.bool | None = ...,
        econo_filter_disabled: _builtins.bool | None = ...,
        econo_ozone_disabled: _builtins.bool | None = ...,
        econo_onzen_disabled: _builtins.bool | None = ...,
        lights2: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["audio", b"audio", "blower_1", b"blower_1", "blower_2", b"blower_2", "econo_filter_disabled", b"econo_filter_disabled", "econo_heater_disabled", b"econo_heater_disabled", "econo_onzen_disabled", b"econo_onzen_disabled", "econo_ozone_disabled", b"econo_ozone_disabled", "exhaust_fan", b"exhaust_fan", "filter", b"filter", "freeze_protect", b"freeze_protect", "heater", b"heater", "lights", b"lights", "lights2", b"lights2", "onzen", b"onzen", "ozone", b"ozone", "pump_1", b"pump_1", "pump_2", b"pump_2", "pump_3", b"pump_3", "pump_4", b"pump_4", "pump_5", b"pump_5", "stand_by", b"stand_by", "temperature", b"temperature"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["audio", b"audio", "blower_1", b"blower_1", "blower_2", b"blower_2", "econo_filter_disabled", b"econo_filter_disabled", "econo_heater_disabled", b"econo_heater_disabled", "econo_onzen_disabled", b"econo_onzen_disabled", "econo_ozone_disabled", b"econo_ozone_disabled", "exhaust_fan", b"exhaust_fan", "filter", b"filter", "freeze_protect", b"freeze_protect", "heater", b"heater", "lights", b"lights", "lights2", b"lights2", "onzen", b"onzen", "ozone", b"ozone", "pump_1", b"pump_1", "pump_2", b"pump_2", "pump_3", b"pump_3", "pump_4", b"pump_4", "pump_5", b"pump_5", "stand_by", b"stand_by", "temperature", b"temperature"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___lpc_live: _TypeAlias = lpc_live  # noqa: Y015

@_typing.final
class lpc_command(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PUMP_1_FIELD_NUMBER: _builtins.int
    PUMP_2_FIELD_NUMBER: _builtins.int
    PUMP_3_FIELD_NUMBER: _builtins.int
    PUMP_4_FIELD_NUMBER: _builtins.int
    PUMP_5_FIELD_NUMBER: _builtins.int
    BLOWER_1_FIELD_NUMBER: _builtins.int
    BLOWER_2_FIELD_NUMBER: _builtins.int
    EXHAUST_FAN_FIELD_NUMBER: _builtins.int
    LIGHTS_FIELD_NUMBER: _builtins.int
    STAND_BY_FIELD_NUMBER: _builtins.int
    FILTER_FIELD_NUMBER: _builtins.int
    OZONE_FIELD_NUMBER: _builtins.int
    ONZEN_FIELD_NUMBER: _builtins.int
    BOOST_FIELD_NUMBER: _builtins.int
    ECONO_FIELD_NUMBER: _builtins.int
    LIGHTS2_FIELD_NUMBER: _builtins.int
    pump_1: Global___PUMP_STATUS.ValueType
    pump_2: Global___PUMP_STATUS.ValueType
    pump_3: Global___PUMP_STATUS.ValueType
    pump_4: Global___PUMP_STATUS.ValueType
    pump_5: Global___PUMP_STATUS.ValueType
    blower_1: Global___BLOWER_STATUS.ValueType
    blower_2: Global___BLOWER_STATUS.ValueType
    exhaust_fan: _builtins.bool
    lights: _builtins.bool
    stand_by: _builtins.bool
    filter: _builtins.bool
    ozone: _builtins.bool
    onzen: _builtins.bool
    boost: _builtins.bool
    econo: _builtins.bool
    lights2: _builtins.bool
    def __init__(
        self,
        *,
        pump_1: Global___PUMP_STATUS.ValueType | None = ...,
        pump_2: Global___PUMP_STATUS.ValueType | None = ...,
        pump_3: Global___PUMP_STATUS.ValueType | None = ...,
        pump_4: Global___PUMP_STATUS.ValueType | None = ...,
        pump_5: Global___PUMP_STATUS.ValueType | None = ...,
        blower_1: Global___BLOWER_STATUS.ValueType | None = ...,
        blower_2: Global___BLOWER_STATUS.ValueType | None = ...,
        exhaust_fan: _builtins.bool | None = ...,
        lights: _builtins.bool | None = ...,
        stand_by: _builtins.bool | None = ...,
        filter: _builtins.bool | None = ...,
        ozone: _builtins.bool | None = ...,
        onzen: _builtins.bool | None = ...,
        boost: _builtins.bool | None = ...,
        econo: _builtins.bool | None = ...,
        lights2: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["blower_1", b"blower_1", "blower_2", b"blower_2", "boost", b"boost", "econo", b"econo", "exhaust_fan", b"exhaust_fan", "filter", b"filter", "lights", b"lights", "lights2", b"lights2", "onzen", b"onzen", "ozone", b"ozone", "pump_1", b"pump_1", "pump_2", b"pump_2", "pump_3", b"pump_3", "pump_4", b"pump_4", "pump_5", b"pump_5", "stand_by", b"stand_by"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blower_1", b"blower_1", "blower_2", b"blower_2", "boost", b"boost", "econo", b"econo", "exhaust_fan", b"exhaust_fan", "filter", b"filter", "lights", b"lights", "lights2", b"lights2", "onzen", b"onzen", "ozone", b"ozone", "pump_1", b"pump_1", "pump_2", b"pump_2", "pump_3", b"pump_3", "pump_4", b"pump_4", "pump_5", b"pump_5", "stand_by", b"stand_by"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___lpc_command: _TypeAlias = lpc_command  # noqa: Y015

@_typing.final
class lpc_info(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    GUID_FIELD_NUMBER: _builtins.int
    FIRMWARE_VERSION_FIELD_NUMBER: _builtins.int
    HARDWARE_VERSION_FIELD_NUMBER: _builtins.int
    PRODUCT_CODE_FIELD_NUMBER: _builtins.int
    BRAND_FIELD_NUMBER: _builtins.int
    TEMPERATURE_MAX_FIELD_NUMBER: _builtins.int
    TEMPERATURE_MIN_FIELD_NUMBER: _builtins.int
    TEMPERATURE_OFFSET_FIELD_NUMBER: _builtins.int
    BLUE_FALLS_SERIAL_NUMBER_FIELD_NUMBER: _builtins.int
    BLUE_FALLS_MODEL_NAME_FIELD_NUMBER: _builtins.int
    AVAILABLE_FIRMWARE_VERSION_FIELD_NUMBER: _builtins.int
    guid: _builtins.str
    firmware_version: _builtins.int
    hardware_version: _builtins.int
    product_code: Global___PRODUCT_CODES.ValueType
    brand: Global___ARCTIC_BRAND.ValueType
    temperature_max: _builtins.int
    temperature_min: _builtins.int
    temperature_offset: _builtins.int
    blue_falls_serial_number: _builtins.str
    blue_falls_model_name: _builtins.str
    available_firmware_version: _builtins.int
    def __init__(
        self,
        *,
        guid: _builtins.str | None = ...,
        firmware_version: _builtins.int | None = ...,
        hardware_version: _builtins.int | None = ...,
        product_code: Global___PRODUCT_CODES.ValueType | None = ...,
        brand: Global___ARCTIC_BRAND.ValueType | None = ...,
        temperature_max: _builtins.int | None = ...,
        temperature_min: _builtins.int | None = ...,
        temperature_offset: _builtins.int | None = ...,
        blue_falls_serial_number: _builtins.str | None = ...,
        blue_falls_model_name: _builtins.str | None = ...,
        available_firmware_version: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["available_firmware_version", b"available_firmware_version", "blue_falls_model_name", b"blue_falls_model_name", "blue_falls_serial_number", b"blue_falls_serial_number", "brand", b"brand", "firmware_version", b"firmware_version", "guid", b"guid", "hardware_version", b"hardware_version", "product_code", b"product_code", "temperature_max", b"temperature_max", "temperature_min", b"temperature_min", "temperature_offset", b"temperature_offset"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["available_firmware_version", b"available_firmware_version", "blue_falls_model_name", b"blue_falls_model_name", "blue_falls_serial_number", b"blue_falls_serial_number", "brand", b"brand", "firmware_version", b"firmware_version", "guid", b"guid", "hardware_version", b"hardware_version", "product_code", b"product_code", "temperature_max", b"temperature_max", "temperature_min", b"temperature_min", "temperature_offset", b"temperature_offset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___lpc_info: _TypeAlias = lpc_info  # noqa: Y015

@_typing.final
class lpc_config(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PUMP_1_FIELD_NUMBER: _builtins.int
    PUMP_2_FIELD_NUMBER: _builtins.int
    PUMP_3_FIELD_NUMBER: _builtins.int
    PUMP_4_FIELD_NUMBER: _builtins.int
    PUMP_5_FIELD_NUMBER: _builtins.int
    BLOWER_1_FIELD_NUMBER: _builtins.int
    BLOWER_2_FIELD_NUMBER: _builtins.int
    OZONE1_FIELD_NUMBER: _builtins.int
    OZONE2_FIELD_NUMBER: _builtins.int
    ONZEN_FIELD_NUMBER: _builtins.int
    EXHAUST_FAN_FIELD_NUMBER: _builtins.int
    pump_1: Global___SPEED.ValueType
    pump_2: Global___SPEED.ValueType
    pump_3: Global___SPEED.ValueType
    pump_4: Global___SPEED.ValueType
    pump_5: Global___SPEED.ValueType
    blower_1: Global___SPEED.ValueType
    blower_2: Global___SPEED.ValueType
    ozone1: _builtins.bool
    ozone2: _builtins.bool
    onzen: _builtins.bool
    exhaust_fan: _builtins.bool
    def __init__(
        self,
        *,
        pump_1: Global___SPEED.ValueType | None = ...,
        pump_2: Global___SPEED.ValueType | None = ...,
        pump_3: Global___SPEED.ValueType | None = ...,
        pump_4: Global___SPEED.ValueType | None = ...,
        pump_5: Global___SPEED.ValueType | None = ...,
        blower_1: Global___SPEED.ValueType | None = ...,
        blower_2: Global___SPEED.ValueType | None = ...,
        ozone1: _builtins.bool | None = ...,
        ozone2: _builtins.bool | None = ...,
        onzen: _builtins.bool | None = ...,
        exhaust_fan: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["blower_1", b"blower_1", "blower_2", b"blower_2", "exhaust_fan", b"exhaust_fan", "onzen", b"onzen", "ozone1", b"ozone1", "ozone2", b"ozone2", "pump_1", b"pump_1", "pump_2", b"pump_2", "pump_3", b"pump_3", "pump_4", b"pump_4", "pump_5", b"pump_5"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blower_1", b"blower_1", "blower_2", b"blower_2", "exhaust_fan", b"exhaust_fan", "onzen", b"onzen", "ozone1", b"ozone1", "ozone2", b"ozone2", "pump_1", b"pump_1", "pump_2", b"pump_2", "pump_3", b"pump_3", "pump_4", b"pump_4", "pump_5", b"pump_5"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___lpc_config: _TypeAlias = lpc_config  # noqa: Y015

@_typing.final
class lpc_power(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POWER_FIELD_NUMBER: _builtins.int
    BREAKER_SIZE_FIELD_NUMBER: _builtins.int
    power: Global___PHASE.ValueType
    breaker_size: _builtins.int
    def __init__(
        self,
        *,
        power: Global___PHASE.ValueType | None = ...,
        breaker_size: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["breaker_size", b"breaker_size", "power", b"power"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["breaker_size", b"breaker_size", "power", b"power"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___lpc_power: _TypeAlias = lpc_power  # noqa: Y015

@_typing.final
class lpc_preferences(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TEMPERATURE_SETPOINT_FIELD_NUMBER: _builtins.int
    TEMPERATURE_DISPLAY_UNIT_FIELD_NUMBER: _builtins.int
    FLASH_LIGHTS_ON_ERROR_FIELD_NUMBER: _builtins.int
    FILTER_SUSPEND_ON_OVERTEMP_FIELD_NUMBER: _builtins.int
    temperature_setpoint: _builtins.int
    temperature_display_unit: Global___TEMPERATURE_UNIT.ValueType
    flash_lights_on_error: _builtins.bool
    filter_suspend_on_overtemp: _builtins.bool
    def __init__(
        self,
        *,
        temperature_setpoint: _builtins.int | None = ...,
        temperature_display_unit: Global___TEMPERATURE_UNIT.ValueType | None = ...,
        flash_lights_on_error: _builtins.bool | None = ...,
        filter_suspend_on_overtemp: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["filter_suspend_on_overtemp", b"filter_suspend_on_overtemp", "flash_lights_on_error", b"flash_lights_on_error", "temperature_display_unit", b"temperature_display_unit", "temperature_setpoint", b"temperature_setpoint"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filter_suspend_on_overtemp", b"filter_suspend_on_overtemp", "flash_lights_on_error", b"flash_lights_on_error", "temperature_display_unit", b"temperature_display_unit", "temperature_setpoint", b"temperature_setpoint"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___lpc_preferences: _TypeAlias = lpc_preferences  # noqa: Y015

@_typing.final
class lpc_lights(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RGB_FIELD_NUMBER: _builtins.int
    EFFECT_FIELD_NUMBER: _builtins.int
    rgb: _builtins.int
    effect: Global___LIGHTS_EFFECT.ValueType
    def __init__(
        self,
        *,
        rgb: _builtins.int | None = ...,
        effect: Global___LIGHTS_EFFECT.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["effect", b"effect", "rgb", b"rgb"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["effect", b"effect", "rgb", b"rgb"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___lpc_lights: _TypeAlias = lpc_lights  # noqa: Y015

@_typing.final
class lpc_schedule(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INDEX_FIELD_NUMBER: _builtins.int
    TYPE_FIELD_NUMBER: _builtins.int
    START_FIELD_NUMBER: _builtins.int
    DURATION_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    SUNDAY_FIELD_NUMBER: _builtins.int
    MONDAY_FIELD_NUMBER: _builtins.int
    TUESDAY_FIELD_NUMBER: _builtins.int
    WEDNESDAY_FIELD_NUMBER: _builtins.int
    THURSDAY_FIELD_NUMBER: _builtins.int
    FRIDAY_FIELD_NUMBER: _builtins.int
    SATURDAY_FIELD_NUMBER: _builtins.int
    index: _builtins.int
    type: Global___SCHEDULE_TYPE.ValueType
    start: _builtins.int
    duration: _builtins.int
    enabled: _builtins.bool
    sunday: _builtins.bool
    monday: _builtins.bool
    tuesday: _builtins.bool
    wednesday: _builtins.bool
    thursday: _builtins.bool
    friday: _builtins.bool
    saturday: _builtins.bool
    def __init__(
        self,
        *,
        index: _builtins.int | None = ...,
        type: Global___SCHEDULE_TYPE.ValueType | None = ...,
        start: _builtins.int | None = ...,
        duration: _builtins.int | None = ...,
        enabled: _builtins.bool | None = ...,
        sunday: _builtins.bool | None = ...,
        monday: _builtins.bool | None = ...,
        tuesday: _builtins.bool | None = ...,
        wednesday: _builtins.bool | None = ...,
        thursday: _builtins.bool | None = ...,
        friday: _builtins.bool | None = ...,
        saturday: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["duration", b"duration", "enabled", b"enabled", "friday", b"friday", "index", b"index", "monday", b"monday", "saturday", b"saturday", "start", b"start", "sunday", b"sunday", "thursday", b"thursday", "tuesday", b"tuesday", "type", b"type", "wednesday", b"wednesday"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["duration", b"duration", "enabled", b"enabled", "friday", b"friday", "index", b"index", "monday", b"monday", "saturday", b"saturday", "start", b"start", "sunday", b"sunday", "thursday", b"thursday", "tuesday", b"tuesday", "type", b"type", "wednesday", b"wednesday"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___lpc_schedule: _TypeAlias = lpc_schedule  # noqa: Y015

@_typing.final
class lpc_clock(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SECOND_FIELD_NUMBER: _builtins.int
    MINUTE_FIELD_NUMBER: _builtins.int
    HOUR_FIELD_NUMBER: _builtins.int
    DAY_OF_MONTH_FIELD_NUMBER: _builtins.int
    DAY_OF_WEEK_FIELD_NUMBER: _builtins.int
    DAY_OF_YEAR_FIELD_NUMBER: _builtins.int
    MONTH_FIELD_NUMBER: _builtins.int
    YEAR_FIELD_NUMBER: _builtins.int
    VALID_FIELD_NUMBER: _builtins.int
    second: _builtins.int
    minute: _builtins.int
    hour: _builtins.int
    day_of_month: _builtins.int
    day_of_week: _builtins.int
    day_of_year: _builtins.int
    month: _builtins.int
    year: _builtins.int
    valid: _builtins.bool
    def __init__(
        self,
        *,
        second: _builtins.int | None = ...,
        minute: _builtins.int | None = ...,
        hour: _builtins.int | None = ...,
        day_of_month: _builtins.int | None = ...,
        day_of_week: _builtins.int | None = ...,
        day_of_year: _builtins.int | None = ...,
        month: _builtins.int | None = ...,
        year: _builtins.int | None = ...,
        valid: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["day_of_month", b"day_of_month", "day_of_week", b"day_of_week", "day_of_year", b"day_of_year", "hour", b"hour", "minute", b"minute", "month", b"month", "second", b"second", "valid", b"valid", "year", b"year"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["day_of_month", b"day_of_month", "day_of_week", b"day_of_week", "day_of_year", b"day_of_year", "hour", b"hour", "minute", b"minute", "month", b"month", "second", b"second", "valid", b"valid", "year", b"year"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___lpc_clock: _TypeAlias = lpc_clock  # noqa: Y015

@_typing.final
class lpc_measurements(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CURRENT_BOARD_FIELD_NUMBER: _builtins.int
    CURRENT_HIGH_POWER_FIELD_NUMBER: _builtins.int
    VOLTAGE_LINE_1_FIELD_NUMBER: _builtins.int
    VOLTAGE_LINE_2_FIELD_NUMBER: _builtins.int
    VOLTAGE_LINE_3_FIELD_NUMBER: _builtins.int
    TEMPERATURE_BOARD_FIELD_NUMBER: _builtins.int
    TEMPERATURE_WATER_FIELD_NUMBER: _builtins.int
    TEMPERATURE_HEATER_FIELD_NUMBER: _builtins.int
    TEMPERATURE_FLOW_FIELD_NUMBER: _builtins.int
    CURRENT_BOARD_RAW_FIELD_NUMBER: _builtins.int
    CURRENT_HIGH_POWER_RAW_FIELD_NUMBER: _builtins.int
    VOLTAGE_LINE_1_RAW_FIELD_NUMBER: _builtins.int
    VOLTAGE_LINE_2_RAW_FIELD_NUMBER: _builtins.int
    VOLTAGE_LINE_3_RAW_FIELD_NUMBER: _builtins.int
    TEMPERATURE_BOARD_RAW_FIELD_NUMBER: _builtins.int
    TEMPERATURE_WATER_RAW_FIELD_NUMBER: _builtins.int
    TEMPERATURE_HEATER_RAW_FIELD_NUMBER: _builtins.int
    TEMPERATURE_FLOW_RAW_FIELD_NUMBER: _builtins.int
    HEATER_VOLTAGE_LINE_1_FIELD_NUMBER: _builtins.int
    HEATER_VOLTAGE_LINE_2_FIELD_NUMBER: _builtins.int
    HEATER_VOLTAGE_LINE_1_RAW_FIELD_NUMBER: _builtins.int
    HEATER_VOLTAGE_LINE_2_RAW_FIELD_NUMBER: _builtins.int
    HEATER_VOLTAGE_FIELD_NUMBER: _builtins.int
    HEATER_VOLTAGE_RAW_FIELD_NUMBER: _builtins.int
    current_board: _builtins.int
    current_high_power: _builtins.int
    voltage_line_1: _builtins.int
    voltage_line_2: _builtins.int
    voltage_line_3: _builtins.int
    temperature_board: _builtins.int
    temperature_water: _builtins.int
    temperature_heater: _builtins.int
    temperature_flow: _builtins.int
    current_board_raw: _builtins.int
    current_high_power_raw: _builtins.int
    voltage_line_1_raw: _builtins.int
    voltage_line_2_raw: _builtins.int
    voltage_line_3_raw: _builtins.int
    temperature_board_raw: _builtins.int
    temperature_water_raw: _builtins.int
    temperature_heater_raw: _builtins.int
    temperature_flow_raw: _builtins.int
    heater_voltage_line_1: _builtins.int
    heater_voltage_line_2: _builtins.int
    heater_voltage_line_1_raw: _builtins.int
    heater_voltage_line_2_raw: _builtins.int
    heater_voltage: _builtins.int
    heater_voltage_raw: _builtins.int
    def __init__(
        self,
        *,
        current_board: _builtins.int | None = ...,
        current_high_power: _builtins.int | None = ...,
        voltage_line_1: _builtins.int | None = ...,
        voltage_line_2: _builtins.int | None = ...,
        voltage_line_3: _builtins.int | None = ...,
        temperature_board: _builtins.int | None = ...,
        temperature_water: _builtins.int | None = ...,
        temperature_heater: _builtins.int | None = ...,
        temperature_flow: _builtins.int | None = ...,
        current_board_raw: _builtins.int | None = ...,
        current_high_power_raw: _builtins.int | None = ...,
        voltage_line_1_raw: _builtins.int | None = ...,
        voltage_line_2_raw: _builtins.int | None = ...,
        voltage_line_3_raw: _builtins.int | None = ...,
        temperature_board_raw: _builtins.int | None = ...,
        temperature_water_raw: _builtins.int | None = ...,
        temperature_heater_raw: _builtins.int | None = ...,
        temperature_flow_raw: _builtins.int | None = ...,
        heater_voltage_line_1: _builtins.int | None = ...,
        heater_voltage_line_2: _builtins.int | None = ...,
        heater_voltage_line_1_raw: _builtins.int | None = ...,
        heater_voltage_line_2_raw: _builtins.int | None = ...,
        heater_voltage: _builtins.int | None = ...,
        heater_voltage_raw: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["current_board", b"current_board", "current_board_raw", b"current_board_raw", "current_high_power", b"current_high_power", "current_high_power_raw", b"current_high_power_raw", "heater_voltage", b"heater_voltage", "heater_voltage_line_1", b"heater_voltage_line_1", "heater_voltage_line_1_raw", b"heater_voltage_line_1_raw", "heater_voltage_line_2", b"heater_voltage_line_2", "heater_voltage_line_2_raw", b"heater_voltage_line_2_raw", "heater_voltage_raw", b"heater_voltage_raw", "temperature_board", b"temperature_board", "temperature_board_raw", b"temperature_board_raw", "temperature_flow", b"temperature_flow", "temperature_flow_raw", b"temperature_flow_raw", "temperature_heater", b"temperature_heater", "temperature_heater_raw", b"temperature_heater_raw", "temperature_water", b"temperature_water", "temperature_water_raw", b"temperature_water_raw", "voltage_line_1", b"voltage_line_1", "voltage_line_1_raw", b"voltage_line_1_raw", "voltage_line_2", b"voltage_line_2", "voltage_line_2_raw", b"voltage_line_2_raw", "voltage_line_3", b"voltage_line_3", "voltage_line_3_raw", b"voltage_line_3_raw"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["current_board", b"current_board", "current_board_raw", b"current_board_raw", "current_high_power", b"current_high_power", "current_high_power_raw", b"current_high_power_raw", "heater_voltage", b"heater_voltage", "heater_voltage_line_1", b"heater_voltage_line_1", "heater_voltage_line_1_raw", b"heater_voltage_line_1_raw", "heater_voltage_line_2", b"heater_voltage_line_2", "heater_voltage_line_2_raw", b"heater_voltage_line_2_raw", "heater_voltage_raw", b"heater_voltage_raw", "temperature_board", b"temperature_board", "temperature_board_raw", b"temperature_board_raw", "temperature_flow", b"temperature_flow", "temperature_flow_raw", b"temperature_flow_raw", "temperature_heater", b"temperature_heater", "temperature_heater_raw", b"temperature_heater_raw", "temperature_water", b"temperature_water", "temperature_water_raw", b"temperature_water_raw", "voltage_line_1", b"voltage_line_1", "voltage_line_1_raw", b"voltage_line_1_raw", "voltage_line_2", b"voltage_line_2", "voltage_line_2_raw", b"voltage_line_2_raw", "voltage_line_3", b"voltage_line_3", "voltage_line_3_raw", b"voltage_line_3_raw"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___lpc_measurements: _TypeAlias = lpc_measurements  # noqa: Y015

@_typing.final
class lpc_peak_devices(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PEAK_HEATER_FIELD_NUMBER: _builtins.int
    PEAK_FILTER_FIELD_NUMBER: _builtins.int
    PEAK_OZONE_FIELD_NUMBER: _builtins.int
    PEAK_ONZEN_FIELD_NUMBER: _builtins.int
    MID_PEAK_HEATER_FIELD_NUMBER: _builtins.int
    MID_PEAK_FILTER_FIELD_NUMBER: _builtins.int
    MID_PEAK_OZONE_FIELD_NUMBER: _builtins.int
    MID_PEAK_ONZEN_FIELD_NUMBER: _builtins.int
    OFF_PEAK_HEATER_FIELD_NUMBER: _builtins.int
    OFF_PEAK_FILTER_FIELD_NUMBER: _builtins.int
    OFF_PEAK_OZONE_FIELD_NUMBER: _builtins.int
    OFF_PEAK_ONZEN_FIELD_NUMBER: _builtins.int
    peak_heater: _builtins.bool
    peak_filter: _builtins.bool
    peak_ozone: _builtins.bool
    peak_onzen: _builtins.bool
    mid_peak_heater: _builtins.bool
    mid_peak_filter: _builtins.bool
    mid_peak_ozone: _builtins.bool
    mid_peak_onzen: _builtins.bool
    off_peak_heater: _builtins.bool
    off_peak_filter: _builtins.bool
    off_peak_ozone: _builtins.bool
    off_peak_onzen: _builtins.bool
    def __init__(
        self,
        *,
        peak_heater: _builtins.bool | None = ...,
        peak_filter: _builtins.bool | None = ...,
        peak_ozone: _builtins.bool | None = ...,
        peak_onzen: _builtins.bool | None = ...,
        mid_peak_heater: _builtins.bool | None = ...,
        mid_peak_filter: _builtins.bool | None = ...,
        mid_peak_ozone: _builtins.bool | None = ...,
        mid_peak_onzen: _builtins.bool | None = ...,
        off_peak_heater: _builtins.bool | None = ...,
        off_peak_filter: _builtins.bool | None = ...,
        off_peak_ozone: _builtins.bool | None = ...,
        off_peak_onzen: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["mid_peak_filter", b"mid_peak_filter", "mid_peak_heater", b"mid_peak_heater", "mid_peak_onzen", b"mid_peak_onzen", "mid_peak_ozone", b"mid_peak_ozone", "off_peak_filter", b"off_peak_filter", "off_peak_heater", b"off_peak_heater", "off_peak_onzen", b"off_peak_onzen", "off_peak_ozone", b"off_peak_ozone", "peak_filter", b"peak_filter", "peak_heater", b"peak_heater", "peak_onzen", b"peak_onzen", "peak_ozone", b"peak_ozone"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["mid_peak_filter", b"mid_peak_filter", "mid_peak_heater", b"mid_peak_heater", "mid_peak_onzen", b"mid_peak_onzen", "mid_peak_ozone", b"mid_peak_ozone", "off_peak_filter", b"off_peak_filter", "off_peak_heater", b"off_peak_heater", "off_peak_onzen", b"off_peak_onzen", "off_peak_ozone", b"off_peak_ozone", "peak_filter", b"peak_filter", "peak_heater", b"peak_heater", "peak_onzen", b"peak_onzen", "peak_ozone", b"peak_ozone"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___lpc_peak_devices: _TypeAlias = lpc_peak_devices  # noqa: Y015

@_typing.final
class lpc_error(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ERROR_FIELD_NUMBER: _builtins.int
    WARNING_FIELD_NUMBER: _builtins.int
    INFO_FIELD_NUMBER: _builtins.int
    DEBUG_FIELD_NUMBER: _builtins.int
    warning: Global___ERROR_CODE.ValueType
    info: Global___ERROR_CODE.ValueType
    debug: Global___ERROR_CODE.ValueType
    @_builtins.property
    def error(self) -> _containers.RepeatedScalarFieldContainer[Global___ERROR_CODE.ValueType]: ...
    def __init__(
        self,
        *,
        error: _abc.Iterable[Global___ERROR_CODE.ValueType] | None = ...,
        warning: Global___ERROR_CODE.ValueType | None = ...,
        info: Global___ERROR_CODE.ValueType | None = ...,
        debug: Global___ERROR_CODE.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["debug", b"debug", "info", b"info", "warning", b"warning"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["debug", b"debug", "error", b"error", "info", b"info", "warning", b"warning"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___lpc_error: _TypeAlias = lpc_error  # noqa: Y015

@_typing.final
class lpc_device_status(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class relay_status(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        RELAY_FIELD_NUMBER: _builtins.int
        LOAD_FIELD_NUMBER: _builtins.int
        ENABLED_FIELD_NUMBER: _builtins.int
        relay: Global___RELAY_ENUM.ValueType
        load: _builtins.int
        enabled: _builtins.bool
        def __init__(
            self,
            *,
            relay: Global___RELAY_ENUM.ValueType | None = ...,
            load: _builtins.int | None = ...,
            enabled: _builtins.bool | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "load", b"load", "relay", b"relay"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["enabled", b"enabled", "load", b"load", "relay", b"relay"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    DEVICE_FIELD_NUMBER: _builtins.int
    SPEED_FIELD_NUMBER: _builtins.int
    CONFIGURED_FIELD_NUMBER: _builtins.int
    RELAYS_FIELD_NUMBER: _builtins.int
    device: Global___DEVICE_ENUM.ValueType
    speed: _builtins.int
    configured: _builtins.bool
    @_builtins.property
    def relays(self) -> _containers.RepeatedCompositeFieldContainer[Global___lpc_device_status.relay_status]: ...
    def __init__(
        self,
        *,
        device: Global___DEVICE_ENUM.ValueType | None = ...,
        speed: _builtins.int | None = ...,
        configured: _builtins.bool | None = ...,
        relays: _abc.Iterable[Global___lpc_device_status.relay_status] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["configured", b"configured", "device", b"device", "speed", b"speed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["configured", b"configured", "device", b"device", "relays", b"relays", "speed", b"speed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___lpc_device_status: _TypeAlias = lpc_device_status  # noqa: Y015

@_typing.final
class lpc_diagnostic_command(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUN_FULL_DIAGNOSTIC_FIELD_NUMBER: _builtins.int
    TEST_DEVICE_FIELD_NUMBER: _builtins.int
    DIAGNOSTIC_STATE_FIELD_NUMBER: _builtins.int
    run_full_diagnostic: _builtins.bool
    test_device: Global___RELAY_ENUM.ValueType
    diagnostic_state: _builtins.bool
    def __init__(
        self,
        *,
        run_full_diagnostic: _builtins.bool | None = ...,
        test_device: Global___RELAY_ENUM.ValueType | None = ...,
        diagnostic_state: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["diagnostic_state", b"diagnostic_state", "run_full_diagnostic", b"run_full_diagnostic", "test_device", b"test_device"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["diagnostic_state", b"diagnostic_state", "run_full_diagnostic", b"run_full_diagnostic", "test_device", b"test_device"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___lpc_diagnostic_command: _TypeAlias = lpc_diagnostic_command  # noqa: Y015

@_typing.final
class debug(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEBUG1_FIELD_NUMBER: _builtins.int
    DEBUG2_FIELD_NUMBER: _builtins.int
    DEBUG3_FIELD_NUMBER: _builtins.int
    DEBUG4_FIELD_NUMBER: _builtins.int
    DEBUG5_FIELD_NUMBER: _builtins.int
    DEBUG6_FIELD_NUMBER: _builtins.int
    DEBUG7_FIELD_NUMBER: _builtins.int
    DEBUG8_FIELD_NUMBER: _builtins.int
    DEBUG9_FIELD_NUMBER: _builtins.int
    DEBUG10_FIELD_NUMBER: _builtins.int
    debug1: _builtins.int
    debug2: _builtins.int
    debug3: _builtins.int
    debug4: _builtins.int
    debug5: _builtins.int
    debug6: _builtins.int
    debug7: _builtins.int
    debug8: _builtins.int
    debug9: _builtins.int
    debug10: _builtins.int
    def __init__(
        self,
        *,
        debug1: _builtins.int | None = ...,
        debug2: _builtins.int | None = ...,
        debug3: _builtins.int | None = ...,
        debug4: _builtins.int | None = ...,
        debug5: _builtins.int | None = ...,
        debug6: _builtins.int | None = ...,
        debug7: _builtins.int | None = ...,
        debug8: _builtins.int | None = ...,
        debug9: _builtins.int | None = ...,
        debug10: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["debug1", b"debug1", "debug10", b"debug10", "debug2", b"debug2", "debug3", b"debug3", "debug4", b"debug4", "debug5", b"debug5", "debug6", b"debug6", "debug7", b"debug7", "debug8", b"debug8", "debug9", b"debug9"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["debug1", b"debug1", "debug10", b"debug10", "debug2", b"debug2", "debug3", b"debug3", "debug4", b"debug4", "debug5", b"debug5", "debug6", b"debug6", "debug7", b"debug7", "debug8", b"debug8", "debug9", b"debug9"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___debug: _TypeAlias = debug  # noqa: Y015

@_typing.final
class relay_debug(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RELAY1_FIELD_NUMBER: _builtins.int
    RELAY2_FIELD_NUMBER: _builtins.int
    RELAY3_FIELD_NUMBER: _builtins.int
    RELAY4_FIELD_NUMBER: _builtins.int
    RELAY5_FIELD_NUMBER: _builtins.int
    RELAY6_FIELD_NUMBER: _builtins.int
    RELAY7_FIELD_NUMBER: _builtins.int
    RELAY8_FIELD_NUMBER: _builtins.int
    RELAY9_FIELD_NUMBER: _builtins.int
    RELAY10_FIELD_NUMBER: _builtins.int
    RELAY11_FIELD_NUMBER: _builtins.int
    RELAY12_FIELD_NUMBER: _builtins.int
    RELAY13_FIELD_NUMBER: _builtins.int
    RELAY14_FIELD_NUMBER: _builtins.int
    RELAY15_FIELD_NUMBER: _builtins.int
    RELAY16_FIELD_NUMBER: _builtins.int
    relay1: _builtins.bool
    relay2: _builtins.bool
    relay3: _builtins.bool
    relay4: _builtins.bool
    relay5: _builtins.bool
    relay6: _builtins.bool
    relay7: _builtins.bool
    relay8: _builtins.bool
    relay9: _builtins.bool
    relay10: _builtins.bool
    relay11: _builtins.bool
    relay12: _builtins.bool
    relay13: _builtins.bool
    relay14: _builtins.bool
    relay15: _builtins.bool
    relay16: _builtins.bool
    def __init__(
        self,
        *,
        relay1: _builtins.bool | None = ...,
        relay2: _builtins.bool | None = ...,
        relay3: _builtins.bool | None = ...,
        relay4: _builtins.bool | None = ...,
        relay5: _builtins.bool | None = ...,
        relay6: _builtins.bool | None = ...,
        relay7: _builtins.bool | None = ...,
        relay8: _builtins.bool | None = ...,
        relay9: _builtins.bool | None = ...,
        relay10: _builtins.bool | None = ...,
        relay11: _builtins.bool | None = ...,
        relay12: _builtins.bool | None = ...,
        relay13: _builtins.bool | None = ...,
        relay14: _builtins.bool | None = ...,
        relay15: _builtins.bool | None = ...,
        relay16: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["relay1", b"relay1", "relay10", b"relay10", "relay11", b"relay11", "relay12", b"relay12", "relay13", b"relay13", "relay14", b"relay14", "relay15", b"relay15", "relay16", b"relay16", "relay2", b"relay2", "relay3", b"relay3", "relay4", b"relay4", "relay5", b"relay5", "relay6", b"relay6", "relay7", b"relay7", "relay8", b"relay8", "relay9", b"relay9"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["relay1", b"relay1", "relay10", b"relay10", "relay11", b"relay11", "relay12", b"relay12", "relay13", b"relay13", "relay14", b"relay14", "relay15", b"relay15", "relay16", b"relay16", "relay2", b"relay2", "relay3", b"relay3", "relay4", b"relay4", "relay5", b"relay5", "relay6", b"relay6", "relay7", b"relay7", "relay8", b"relay8", "relay9", b"relay9"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___relay_debug: _TypeAlias = relay_debug  # noqa: Y015

@_typing.final
class lpc_load(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RELAY_K1_FIELD_NUMBER: _builtins.int
    RELAY_K2_FIELD_NUMBER: _builtins.int
    RELAY_K3_FIELD_NUMBER: _builtins.int
    RELAY_K4_FIELD_NUMBER: _builtins.int
    RELAY_K5_FIELD_NUMBER: _builtins.int
    RELAY_K6_FIELD_NUMBER: _builtins.int
    RELAY_K7_FIELD_NUMBER: _builtins.int
    RELAY_K8_FIELD_NUMBER: _builtins.int
    RELAY_K9_FIELD_NUMBER: _builtins.int
    RELAY_K10_FIELD_NUMBER: _builtins.int
    RELAY_K14_FIELD_NUMBER: _builtins.int
    RELAY_K17_FIELD_NUMBER: _builtins.int
    relay_k1: _builtins.int
    relay_k2: _builtins.int
    relay_k3: _builtins.int
    relay_k4: _builtins.int
    relay_k5: _builtins.int
    relay_k6: _builtins.int
    relay_k7: _builtins.int
    relay_k8: _builtins.int
    relay_k9: _builtins.int
    relay_k10: _builtins.int
    relay_k14: _builtins.int
    relay_k17: _builtins.int
    def __init__(
        self,
        *,
        relay_k1: _builtins.int | None = ...,
        relay_k2: _builtins.int | None = ...,
        relay_k3: _builtins.int | None = ...,
        relay_k4: _builtins.int | None = ...,
        relay_k5: _builtins.int | None = ...,
        relay_k6: _builtins.int | None = ...,
        relay_k7: _builtins.int | None = ...,
        relay_k8: _builtins.int | None = ...,
        relay_k9: _builtins.int | None = ...,
        relay_k10: _builtins.int | None = ...,
        relay_k14: _builtins.int | None = ...,
        relay_k17: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["relay_k1", b"relay_k1", "relay_k10", b"relay_k10", "relay_k14", b"relay_k14", "relay_k17", b"relay_k17", "relay_k2", b"relay_k2", "relay_k3", b"relay_k3", "relay_k4", b"relay_k4", "relay_k5", b"relay_k5", "relay_k6", b"relay_k6", "relay_k7", b"relay_k7", "relay_k8", b"relay_k8", "relay_k9", b"relay_k9"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["relay_k1", b"relay_k1", "relay_k10", b"relay_k10", "relay_k14", b"relay_k14", "relay_k17", b"relay_k17", "relay_k2", b"relay_k2", "relay_k3", b"relay_k3", "relay_k4", b"relay_k4", "relay_k5", b"relay_k5", "relay_k6", b"relay_k6", "relay_k7", b"relay_k7", "relay_k8", b"relay_k8", "relay_k9", b"relay_k9"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___lpc_load: _TypeAlias = lpc_load  # noqa: Y015
