# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mobile_available_spas.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'mobile_available_spas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bmobile_available_spas.proto\x12\x13\x63om.levven.protobuf\"\xe0\x01\n\x15mobile_available_spas\x12H\n\tmobileSpa\x18\x01 \x03(\x0b\x32\x35.com.levven.protobuf.mobile_available_spas.mobile_spa\x1a}\n\nmobile_spa\x12\x0c\n\x04guid\x18\x01 \x01(\t\x12\x15\n\rpackProductId\x18\x02 \x01(\t\x12\x13\n\x0bproductCode\x18\x03 \x01(\x05\x12\x10\n\x08nickName\x18\x04 \x01(\t\x12\x11\n\tconnected\x18\x05 \x01(\x08\x12\x10\n\x08serverId\x18\x06 \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mobile_available_spas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOBILE_AVAILABLE_SPAS']._serialized_start=53
  _globals['_MOBILE_AVAILABLE_SPAS']._serialized_end=277
  _globals['_MOBILE_AVAILABLE_SPAS_MOBILE_SPA']._serialized_start=152
  _globals['_MOBILE_AVAILABLE_SPAS_MOBILE_SPA']._serialized_end=277
# @@protoc_insertion_point(module_scope)
