"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class mobile_available_spas(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class mobile_spa(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        GUID_FIELD_NUMBER: _builtins.int
        PACKPRODUCTID_FIELD_NUMBER: _builtins.int
        PRODUCTCODE_FIELD_NUMBER: _builtins.int
        NICKNAME_FIELD_NUMBER: _builtins.int
        CONNECTED_FIELD_NUMBER: _builtins.int
        SERVERID_FIELD_NUMBER: _builtins.int
        guid: _builtins.str
        packProductId: _builtins.str
        productCode: _builtins.int
        nickName: _builtins.str
        connected: _builtins.bool
        serverId: _builtins.str
        def __init__(
            self,
            *,
            guid: _builtins.str | None = ...,
            packProductId: _builtins.str | None = ...,
            productCode: _builtins.int | None = ...,
            nickName: _builtins.str | None = ...,
            connected: _builtins.bool | None = ...,
            serverId: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["connected", b"connected", "guid", b"guid", "nickName", b"nickName", "packProductId", b"packProductId", "productCode", b"productCode", "serverId", b"serverId"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["connected", b"connected", "guid", b"guid", "nickName", b"nickName", "packProductId", b"packProductId", "productCode", b"productCode", "serverId", b"serverId"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    MOBILESPA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def mobileSpa(self) -> _containers.RepeatedCompositeFieldContainer[Global___mobile_available_spas.mobile_spa]: ...
    def __init__(
        self,
        *,
        mobileSpa: _abc.Iterable[Global___mobile_available_spas.mobile_spa] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["mobileSpa", b"mobileSpa"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___mobile_available_spas: _TypeAlias = mobile_available_spas  # noqa: Y015
