"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class spa_settings(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    MAX_FILTRATION_FREQUENCY_FIELD_NUMBER: _builtins.int
    MIN_FILTRATION_FREQUENCY_FIELD_NUMBER: _builtins.int
    FILTRATION_FREQUENCY_FIELD_NUMBER: _builtins.int
    MAX_FILTRATION_DURATION_FIELD_NUMBER: _builtins.int
    MIN_FILTRATION_DURATION_FIELD_NUMBER: _builtins.int
    FILTRATION_DURATION_FIELD_NUMBER: _builtins.int
    MAX_ONZEN_HOURS_FIELD_NUMBER: _builtins.int
    MIN_ONZEN_HOURS_FIELD_NUMBER: _builtins.int
    ONZEN_HOURS_FIELD_NUMBER: _builtins.int
    MAX_ONZEN_CYCLES_FIELD_NUMBER: _builtins.int
    MIN_ONZEN_CYCLES_FIELD_NUMBER: _builtins.int
    ONZEN_CYCLES_FIELD_NUMBER: _builtins.int
    MAX_OZONE_HOURS_FIELD_NUMBER: _builtins.int
    MIN_OZONE_HOURS_FIELD_NUMBER: _builtins.int
    OZONE_HOURS_FIELD_NUMBER: _builtins.int
    MAX_OZONE_CYCLES_FIELD_NUMBER: _builtins.int
    MIN_OZONE_CYCLES_FIELD_NUMBER: _builtins.int
    OZONE_CYCLES_FIELD_NUMBER: _builtins.int
    FILTER_SUSPENSION_FIELD_NUMBER: _builtins.int
    FLASH_LIGHTS_ON_ERROR_FIELD_NUMBER: _builtins.int
    TEMPERATURE_OFFSET_FIELD_NUMBER: _builtins.int
    SAUNA_DURATION_FIELD_NUMBER: _builtins.int
    MIN_TEMPERATURE_FIELD_NUMBER: _builtins.int
    MAX_TEMPERATURE_FIELD_NUMBER: _builtins.int
    FILTRATION_OFFSET_FIELD_NUMBER: _builtins.int
    SPABOY_HOURS_FIELD_NUMBER: _builtins.int
    max_filtration_frequency: _builtins.int
    min_filtration_frequency: _builtins.int
    filtration_frequency: _builtins.int
    max_filtration_duration: _builtins.int
    min_filtration_duration: _builtins.int
    filtration_duration: _builtins.int
    max_onzen_hours: _builtins.int
    min_onzen_hours: _builtins.int
    onzen_hours: _builtins.int
    max_onzen_cycles: _builtins.int
    min_onzen_cycles: _builtins.int
    onzen_cycles: _builtins.int
    max_ozone_hours: _builtins.int
    min_ozone_hours: _builtins.int
    ozone_hours: _builtins.int
    max_ozone_cycles: _builtins.int
    min_ozone_cycles: _builtins.int
    ozone_cycles: _builtins.int
    filter_suspension: _builtins.bool
    flash_lights_on_error: _builtins.bool
    temperature_offset: _builtins.int
    sauna_duration: _builtins.int
    min_temperature: _builtins.int
    max_temperature: _builtins.int
    filtration_offset: _builtins.int
    spaboy_hours: _builtins.int
    def __init__(
        self,
        *,
        max_filtration_frequency: _builtins.int | None = ...,
        min_filtration_frequency: _builtins.int | None = ...,
        filtration_frequency: _builtins.int | None = ...,
        max_filtration_duration: _builtins.int | None = ...,
        min_filtration_duration: _builtins.int | None = ...,
        filtration_duration: _builtins.int | None = ...,
        max_onzen_hours: _builtins.int | None = ...,
        min_onzen_hours: _builtins.int | None = ...,
        onzen_hours: _builtins.int | None = ...,
        max_onzen_cycles: _builtins.int | None = ...,
        min_onzen_cycles: _builtins.int | None = ...,
        onzen_cycles: _builtins.int | None = ...,
        max_ozone_hours: _builtins.int | None = ...,
        min_ozone_hours: _builtins.int | None = ...,
        ozone_hours: _builtins.int | None = ...,
        max_ozone_cycles: _builtins.int | None = ...,
        min_ozone_cycles: _builtins.int | None = ...,
        ozone_cycles: _builtins.int | None = ...,
        filter_suspension: _builtins.bool | None = ...,
        flash_lights_on_error: _builtins.bool | None = ...,
        temperature_offset: _builtins.int | None = ...,
        sauna_duration: _builtins.int | None = ...,
        min_temperature: _builtins.int | None = ...,
        max_temperature: _builtins.int | None = ...,
        filtration_offset: _builtins.int | None = ...,
        spaboy_hours: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["filter_suspension", b"filter_suspension", "filtration_duration", b"filtration_duration", "filtration_frequency", b"filtration_frequency", "filtration_offset", b"filtration_offset", "flash_lights_on_error", b"flash_lights_on_error", "max_filtration_duration", b"max_filtration_duration", "max_filtration_frequency", b"max_filtration_frequency", "max_onzen_cycles", b"max_onzen_cycles", "max_onzen_hours", b"max_onzen_hours", "max_ozone_cycles", b"max_ozone_cycles", "max_ozone_hours", b"max_ozone_hours", "max_temperature", b"max_temperature", "min_filtration_duration", b"min_filtration_duration", "min_filtration_frequency", b"min_filtration_frequency", "min_onzen_cycles", b"min_onzen_cycles", "min_onzen_hours", b"min_onzen_hours", "min_ozone_cycles", b"min_ozone_cycles", "min_ozone_hours", b"min_ozone_hours", "min_temperature", b"min_temperature", "onzen_cycles", b"onzen_cycles", "onzen_hours", b"onzen_hours", "ozone_cycles", b"ozone_cycles", "ozone_hours", b"ozone_hours", "sauna_duration", b"sauna_duration", "spaboy_hours", b"spaboy_hours", "temperature_offset", b"temperature_offset"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filter_suspension", b"filter_suspension", "filtration_duration", b"filtration_duration", "filtration_frequency", b"filtration_frequency", "filtration_offset", b"filtration_offset", "flash_lights_on_error", b"flash_lights_on_error", "max_filtration_duration", b"max_filtration_duration", "max_filtration_frequency", b"max_filtration_frequency", "max_onzen_cycles", b"max_onzen_cycles", "max_onzen_hours", b"max_onzen_hours", "max_ozone_cycles", b"max_ozone_cycles", "max_ozone_hours", b"max_ozone_hours", "max_temperature", b"max_temperature", "min_filtration_duration", b"min_filtration_duration", "min_filtration_frequency", b"min_filtration_frequency", "min_onzen_cycles", b"min_onzen_cycles", "min_onzen_hours", b"min_onzen_hours", "min_ozone_cycles", b"min_ozone_cycles", "min_ozone_hours", b"min_ozone_hours", "min_temperature", b"min_temperature", "onzen_cycles", b"onzen_cycles", "onzen_hours", b"onzen_hours", "ozone_cycles", b"ozone_cycles", "ozone_hours", b"ozone_hours", "sauna_duration", b"sauna_duration", "spaboy_hours", b"spaboy_hours", "temperature_offset", b"temperature_offset"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___spa_settings: _TypeAlias = spa_settings  # noqa: Y015
