"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class spa_clock(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    YEAR_FIELD_NUMBER: _builtins.int
    MONTH_FIELD_NUMBER: _builtins.int
    DAY_FIELD_NUMBER: _builtins.int
    HOUR_FIELD_NUMBER: _builtins.int
    MINUTE_FIELD_NUMBER: _builtins.int
    SECOND_FIELD_NUMBER: _builtins.int
    year: _builtins.int
    month: _builtins.int
    day: _builtins.int
    hour: _builtins.int
    minute: _builtins.int
    second: _builtins.int
    def __init__(
        self,
        *,
        year: _builtins.int | None = ...,
        month: _builtins.int | None = ...,
        day: _builtins.int | None = ...,
        hour: _builtins.int | None = ...,
        minute: _builtins.int | None = ...,
        second: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["day", b"day", "hour", b"hour", "minute", b"minute", "month", b"month", "second", b"second", "year", b"year"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["day", b"day", "hour", b"hour", "minute", b"minute", "month", b"month", "second", b"second", "year", b"year"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___spa_clock: _TypeAlias = spa_clock  # noqa: Y015
