"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _SET_PUMP_STATUS:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SET_PUMP_STATUSEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SET_PUMP_STATUS.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    OFF: _SET_PUMP_STATUS.ValueType  # 0
    LOW: _SET_PUMP_STATUS.ValueType  # 1
    HIGH: _SET_PUMP_STATUS.ValueType  # 2

class SET_PUMP_STATUS(_SET_PUMP_STATUS, metaclass=_SET_PUMP_STATUSEnumTypeWrapper): ...

OFF: SET_PUMP_STATUS.ValueType  # 0
LOW: SET_PUMP_STATUS.ValueType  # 1
HIGH: SET_PUMP_STATUS.ValueType  # 2
Global___SET_PUMP_STATUS: _TypeAlias = SET_PUMP_STATUS  # noqa: Y015

class _SET_SAUNA_STATE:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SET_SAUNA_STATEEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SET_SAUNA_STATE.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    IDLE: _SET_SAUNA_STATE.ValueType  # 0
    TIMER: _SET_SAUNA_STATE.ValueType  # 1
    PRESET_A: _SET_SAUNA_STATE.ValueType  # 2
    PRESET_B: _SET_SAUNA_STATE.ValueType  # 3
    PRESET_C: _SET_SAUNA_STATE.ValueType  # 4

class SET_SAUNA_STATE(_SET_SAUNA_STATE, metaclass=_SET_SAUNA_STATEEnumTypeWrapper): ...

IDLE: SET_SAUNA_STATE.ValueType  # 0
TIMER: SET_SAUNA_STATE.ValueType  # 1
PRESET_A: SET_SAUNA_STATE.ValueType  # 2
PRESET_B: SET_SAUNA_STATE.ValueType  # 3
PRESET_C: SET_SAUNA_STATE.ValueType  # 4
Global___SET_SAUNA_STATE: _TypeAlias = SET_SAUNA_STATE  # noqa: Y015

@_typing.final
class spa_command(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SET_TEMPERATURE_SETPOINT_FAHRENHEIT_FIELD_NUMBER: _builtins.int
    SET_PUMP_1_FIELD_NUMBER: _builtins.int
    SET_PUMP_2_FIELD_NUMBER: _builtins.int
    SET_PUMP_3_FIELD_NUMBER: _builtins.int
    SET_PUMP_4_FIELD_NUMBER: _builtins.int
    SET_PUMP_5_FIELD_NUMBER: _builtins.int
    SET_BLOWER_1_FIELD_NUMBER: _builtins.int
    SET_BLOWER_2_FIELD_NUMBER: _builtins.int
    SET_LIGHTS_FIELD_NUMBER: _builtins.int
    SET_STEREO_FIELD_NUMBER: _builtins.int
    SET_FILTER_FIELD_NUMBER: _builtins.int
    SET_ONZEN_FIELD_NUMBER: _builtins.int
    SET_OZONE_FIELD_NUMBER: _builtins.int
    SET_EXHAUST_FAN_FIELD_NUMBER: _builtins.int
    SET_SAUNA_STATE_FIELD_NUMBER: _builtins.int
    SET_SAUNA_TIME_LEFT_FIELD_NUMBER: _builtins.int
    ALL_ON_FIELD_NUMBER: _builtins.int
    SET_FOGGER_FIELD_NUMBER: _builtins.int
    SPABOY_BOOST_FIELD_NUMBER: _builtins.int
    SET_ORP_LEVEL_LOW_FIELD_NUMBER: _builtins.int
    SET_ORP_LEVEL_HIGH_FIELD_NUMBER: _builtins.int
    set_temperature_setpoint_fahrenheit: _builtins.int
    set_pump_1: Global___SET_PUMP_STATUS.ValueType
    set_pump_2: Global___SET_PUMP_STATUS.ValueType
    set_pump_3: Global___SET_PUMP_STATUS.ValueType
    set_pump_4: Global___SET_PUMP_STATUS.ValueType
    set_pump_5: Global___SET_PUMP_STATUS.ValueType
    set_blower_1: Global___SET_PUMP_STATUS.ValueType
    set_blower_2: Global___SET_PUMP_STATUS.ValueType
    set_lights: _builtins.bool
    set_stereo: _builtins.bool
    set_filter: _builtins.bool
    set_onzen: _builtins.bool
    set_ozone: _builtins.bool
    set_exhaust_fan: _builtins.bool
    set_sauna_state: Global___SET_SAUNA_STATE.ValueType
    set_sauna_time_left: _builtins.int
    all_on: _builtins.bool
    set_fogger: _builtins.bool
    spaboy_boost: _builtins.bool
    set_orp_level_low: _builtins.int
    set_orp_level_high: _builtins.int
    def __init__(
        self,
        *,
        set_temperature_setpoint_fahrenheit: _builtins.int | None = ...,
        set_pump_1: Global___SET_PUMP_STATUS.ValueType | None = ...,
        set_pump_2: Global___SET_PUMP_STATUS.ValueType | None = ...,
        set_pump_3: Global___SET_PUMP_STATUS.ValueType | None = ...,
        set_pump_4: Global___SET_PUMP_STATUS.ValueType | None = ...,
        set_pump_5: Global___SET_PUMP_STATUS.ValueType | None = ...,
        set_blower_1: Global___SET_PUMP_STATUS.ValueType | None = ...,
        set_blower_2: Global___SET_PUMP_STATUS.ValueType | None = ...,
        set_lights: _builtins.bool | None = ...,
        set_stereo: _builtins.bool | None = ...,
        set_filter: _builtins.bool | None = ...,
        set_onzen: _builtins.bool | None = ...,
        set_ozone: _builtins.bool | None = ...,
        set_exhaust_fan: _builtins.bool | None = ...,
        set_sauna_state: Global___SET_SAUNA_STATE.ValueType | None = ...,
        set_sauna_time_left: _builtins.int | None = ...,
        all_on: _builtins.bool | None = ...,
        set_fogger: _builtins.bool | None = ...,
        spaboy_boost: _builtins.bool | None = ...,
        set_orp_level_low: _builtins.int | None = ...,
        set_orp_level_high: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["all_on", b"all_on", "set_blower_1", b"set_blower_1", "set_blower_2", b"set_blower_2", "set_exhaust_fan", b"set_exhaust_fan", "set_filter", b"set_filter", "set_fogger", b"set_fogger", "set_lights", b"set_lights", "set_onzen", b"set_onzen", "set_orp_level_high", b"set_orp_level_high", "set_orp_level_low", b"set_orp_level_low", "set_ozone", b"set_ozone", "set_pump_1", b"set_pump_1", "set_pump_2", b"set_pump_2", "set_pump_3", b"set_pump_3", "set_pump_4", b"set_pump_4", "set_pump_5", b"set_pump_5", "set_sauna_state", b"set_sauna_state", "set_sauna_time_left", b"set_sauna_time_left", "set_stereo", b"set_stereo", "set_temperature_setpoint_fahrenheit", b"set_temperature_setpoint_fahrenheit", "spaboy_boost", b"spaboy_boost"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["all_on", b"all_on", "set_blower_1", b"set_blower_1", "set_blower_2", b"set_blower_2", "set_exhaust_fan", b"set_exhaust_fan", "set_filter", b"set_filter", "set_fogger", b"set_fogger", "set_lights", b"set_lights", "set_onzen", b"set_onzen", "set_orp_level_high", b"set_orp_level_high", "set_orp_level_low", b"set_orp_level_low", "set_ozone", b"set_ozone", "set_pump_1", b"set_pump_1", "set_pump_2", b"set_pump_2", "set_pump_3", b"set_pump_3", "set_pump_4", b"set_pump_4", "set_pump_5", b"set_pump_5", "set_sauna_state", b"set_sauna_state", "set_sauna_time_left", b"set_sauna_time_left", "set_stereo", b"set_stereo", "set_temperature_setpoint_fahrenheit", b"set_temperature_setpoint_fahrenheit", "spaboy_boost", b"spaboy_boost"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___spa_command: _TypeAlias = spa_command  # noqa: Y015
