# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SpaInformation.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'SpaInformation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14SpaInformation.proto\x12\x1c\x63om.levven.protobuf.coldfire\"\xaa\x03\n\x0fspa_information\x12\x1a\n\x12pack_serial_number\x18\x01 \x01(\t\x12\x1d\n\x15pack_firmware_version\x18\x02 \x01(\t\x12\x1d\n\x15pack_hardware_version\x18\x03 \x01(\t\x12\x17\n\x0fpack_product_id\x18\x04 \x01(\t\x12\x15\n\rpack_board_id\x18\x05 \x01(\t\x12\x1a\n\x12topside_product_id\x18\x06 \x01(\t\x12 \n\x18topside_software_version\x18\x07 \x01(\t\x12\x0c\n\x04guid\x18\x08 \x01(\t\x12\x38\n\x08spa_type\x18\t \x01(\x0e\x32&.com.levven.protobuf.coldfire.SPA_TYPE\x12\x1c\n\x14website_registration\x18\n \x01(\x08\x12$\n\x1cwebsite_registration_confirm\x18\x0b \x01(\x08\x12\x13\n\x0bmac_address\x18\x0c \x01(\x0c\x12\x18\n\x10\x66irmware_version\x18\r \x01(\r\x12\x14\n\x0cproduct_code\x18\x0e \x01(\r*0\n\x08SPA_TYPE\x12\x0b\n\x07HOT_TUB\x10\x00\x12\x0c\n\x08\x43OLD_TUB\x10\x01\x12\t\n\x05SAUNA\x10\x02*\x85\x02\n\x0cPRODUCT_CODE\x12\x15\n\x0fSPA_NA_COLDFIRE\x10\x80\x80\x04\x12\x17\n\x11SPA_EURO_COLDFIRE\x10\x81\x80\x04\x12\x10\n\nSPA_NA_LPC\x10\x82\x80\x04\x12\x12\n\x0cSPA_EURO_LPC\x10\x83\x80\x04\x12\x14\n\x0eSAUNA_COLDFIRE\x10\x80\x80\x08\x12\x0f\n\tSAUNA_LPC\x10\x81\x80\x08\x12\x17\n\x11\x43OLD_TUB_COLDFIRE\x10\x80\x80\x0c\x12\x12\n\x0c\x43OLD_TUB_LPC\x10\x81\x80\x0c\x12\x14\n\x0ePERIPHERAL_WAU\x10\x80\x80\x10\x12\x16\n\x10PERIPHERAL_ONZEN\x10\x81\x80\x10\x12\x1d\n\x17PERIPHERAL_TOP_SIDE_A10\x10\x82\x80\x10')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SpaInformation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPA_TYPE']._serialized_start=483
  _globals['_SPA_TYPE']._serialized_end=531
  _globals['_PRODUCT_CODE']._serialized_start=534
  _globals['_PRODUCT_CODE']._serialized_end=795
  _globals['_SPA_INFORMATION']._serialized_start=55
  _globals['_SPA_INFORMATION']._serialized_end=481
# @@protoc_insertion_point(module_scope)
