"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _SPA_TYPE:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SPA_TYPEEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SPA_TYPE.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    HOT_TUB: _SPA_TYPE.ValueType  # 0
    COLD_TUB: _SPA_TYPE.ValueType  # 1
    SAUNA: _SPA_TYPE.ValueType  # 2

class SPA_TYPE(_SPA_TYPE, metaclass=_SPA_TYPEEnumTypeWrapper): ...

HOT_TUB: SPA_TYPE.ValueType  # 0
COLD_TUB: SPA_TYPE.ValueType  # 1
SAUNA: SPA_TYPE.ValueType  # 2
Global___SPA_TYPE: _TypeAlias = SPA_TYPE  # noqa: Y015

class _PRODUCT_CODE:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PRODUCT_CODEEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PRODUCT_CODE.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SPA_NA_COLDFIRE: _PRODUCT_CODE.ValueType  # 65536
    SPA_EURO_COLDFIRE: _PRODUCT_CODE.ValueType  # 65537
    SPA_NA_LPC: _PRODUCT_CODE.ValueType  # 65538
    SPA_EURO_LPC: _PRODUCT_CODE.ValueType  # 65539
    SAUNA_COLDFIRE: _PRODUCT_CODE.ValueType  # 131072
    SAUNA_LPC: _PRODUCT_CODE.ValueType  # 131073
    COLD_TUB_COLDFIRE: _PRODUCT_CODE.ValueType  # 196608
    COLD_TUB_LPC: _PRODUCT_CODE.ValueType  # 196609
    PERIPHERAL_WAU: _PRODUCT_CODE.ValueType  # 262144
    PERIPHERAL_ONZEN: _PRODUCT_CODE.ValueType  # 262145
    PERIPHERAL_TOP_SIDE_A10: _PRODUCT_CODE.ValueType  # 262146

class PRODUCT_CODE(_PRODUCT_CODE, metaclass=_PRODUCT_CODEEnumTypeWrapper): ...

SPA_NA_COLDFIRE: PRODUCT_CODE.ValueType  # 65536
SPA_EURO_COLDFIRE: PRODUCT_CODE.ValueType  # 65537
SPA_NA_LPC: PRODUCT_CODE.ValueType  # 65538
SPA_EURO_LPC: PRODUCT_CODE.ValueType  # 65539
SAUNA_COLDFIRE: PRODUCT_CODE.ValueType  # 131072
SAUNA_LPC: PRODUCT_CODE.ValueType  # 131073
COLD_TUB_COLDFIRE: PRODUCT_CODE.ValueType  # 196608
COLD_TUB_LPC: PRODUCT_CODE.ValueType  # 196609
PERIPHERAL_WAU: PRODUCT_CODE.ValueType  # 262144
PERIPHERAL_ONZEN: PRODUCT_CODE.ValueType  # 262145
PERIPHERAL_TOP_SIDE_A10: PRODUCT_CODE.ValueType  # 262146
Global___PRODUCT_CODE: _TypeAlias = PRODUCT_CODE  # noqa: Y015

@_typing.final
class spa_information(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PACK_SERIAL_NUMBER_FIELD_NUMBER: _builtins.int
    PACK_FIRMWARE_VERSION_FIELD_NUMBER: _builtins.int
    PACK_HARDWARE_VERSION_FIELD_NUMBER: _builtins.int
    PACK_PRODUCT_ID_FIELD_NUMBER: _builtins.int
    PACK_BOARD_ID_FIELD_NUMBER: _builtins.int
    TOPSIDE_PRODUCT_ID_FIELD_NUMBER: _builtins.int
    TOPSIDE_SOFTWARE_VERSION_FIELD_NUMBER: _builtins.int
    GUID_FIELD_NUMBER: _builtins.int
    SPA_TYPE_FIELD_NUMBER: _builtins.int
    WEBSITE_REGISTRATION_FIELD_NUMBER: _builtins.int
    WEBSITE_REGISTRATION_CONFIRM_FIELD_NUMBER: _builtins.int
    MAC_ADDRESS_FIELD_NUMBER: _builtins.int
    FIRMWARE_VERSION_FIELD_NUMBER: _builtins.int
    PRODUCT_CODE_FIELD_NUMBER: _builtins.int
    pack_serial_number: _builtins.str
    pack_firmware_version: _builtins.str
    pack_hardware_version: _builtins.str
    pack_product_id: _builtins.str
    pack_board_id: _builtins.str
    topside_product_id: _builtins.str
    topside_software_version: _builtins.str
    guid: _builtins.str
    spa_type: Global___SPA_TYPE.ValueType
    website_registration: _builtins.bool
    website_registration_confirm: _builtins.bool
    mac_address: _builtins.bytes
    firmware_version: _builtins.int
    product_code: _builtins.int
    def __init__(
        self,
        *,
        pack_serial_number: _builtins.str | None = ...,
        pack_firmware_version: _builtins.str | None = ...,
        pack_hardware_version: _builtins.str | None = ...,
        pack_product_id: _builtins.str | None = ...,
        pack_board_id: _builtins.str | None = ...,
        topside_product_id: _builtins.str | None = ...,
        topside_software_version: _builtins.str | None = ...,
        guid: _builtins.str | None = ...,
        spa_type: Global___SPA_TYPE.ValueType | None = ...,
        website_registration: _builtins.bool | None = ...,
        website_registration_confirm: _builtins.bool | None = ...,
        mac_address: _builtins.bytes | None = ...,
        firmware_version: _builtins.int | None = ...,
        product_code: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["firmware_version", b"firmware_version", "guid", b"guid", "mac_address", b"mac_address", "pack_board_id", b"pack_board_id", "pack_firmware_version", b"pack_firmware_version", "pack_hardware_version", b"pack_hardware_version", "pack_product_id", b"pack_product_id", "pack_serial_number", b"pack_serial_number", "product_code", b"product_code", "spa_type", b"spa_type", "topside_product_id", b"topside_product_id", "topside_software_version", b"topside_software_version", "website_registration", b"website_registration", "website_registration_confirm", b"website_registration_confirm"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["firmware_version", b"firmware_version", "guid", b"guid", "mac_address", b"mac_address", "pack_board_id", b"pack_board_id", "pack_firmware_version", b"pack_firmware_version", "pack_hardware_version", b"pack_hardware_version", "pack_product_id", b"pack_product_id", "pack_serial_number", b"pack_serial_number", "product_code", b"product_code", "spa_type", b"spa_type", "topside_product_id", b"topside_product_id", "topside_software_version", b"topside_software_version", "website_registration", b"website_registration", "website_registration_confirm", b"website_registration_confirm"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___spa_information: _TypeAlias = spa_information  # noqa: Y015
