"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class spa_onzen_settings(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PACK_SERIAL_NUMBER_FIELD_NUMBER: _builtins.int
    ORP_LOW_FIELD_NUMBER: _builtins.int
    ORP_HIGH_FIELD_NUMBER: _builtins.int
    pack_serial_number: _builtins.str
    orp_low: _builtins.int
    orp_high: _builtins.int
    def __init__(
        self,
        *,
        pack_serial_number: _builtins.str | None = ...,
        orp_low: _builtins.int | None = ...,
        orp_high: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["orp_high", b"orp_high", "orp_low", b"orp_low", "pack_serial_number", b"pack_serial_number"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["orp_high", b"orp_high", "orp_low", b"orp_low", "pack_serial_number", b"pack_serial_number"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___spa_onzen_settings: _TypeAlias = spa_onzen_settings  # noqa: Y015
