"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _AUTHENTICATE_STATUS:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _AUTHENTICATE_STATUSEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_AUTHENTICATE_STATUS.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    AUTHENTICATE_SUCCESS: _AUTHENTICATE_STATUS.ValueType  # 0
    AUTHENTICATE_FAILURE: _AUTHENTICATE_STATUS.ValueType  # 1

class AUTHENTICATE_STATUS(_AUTHENTICATE_STATUS, metaclass=_AUTHENTICATE_STATUSEnumTypeWrapper): ...

AUTHENTICATE_SUCCESS: AUTHENTICATE_STATUS.ValueType  # 0
AUTHENTICATE_FAILURE: AUTHENTICATE_STATUS.ValueType  # 1
Global___AUTHENTICATE_STATUS: _TypeAlias = AUTHENTICATE_STATUS  # noqa: Y015

@_typing.final
class mobile_authenticate(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    USERNAME_FIELD_NUMBER: _builtins.int
    SALT_FIELD_NUMBER: _builtins.int
    HASH_FIELD_NUMBER: _builtins.int
    AUTH_STATUS_FIELD_NUMBER: _builtins.int
    username: _builtins.str
    salt: _builtins.str
    hash: _builtins.str
    auth_status: Global___AUTHENTICATE_STATUS.ValueType
    def __init__(
        self,
        *,
        username: _builtins.str | None = ...,
        salt: _builtins.str | None = ...,
        hash: _builtins.str | None = ...,
        auth_status: Global___AUTHENTICATE_STATUS.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["auth_status", b"auth_status", "hash", b"hash", "salt", b"salt", "username", b"username"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["auth_status", b"auth_status", "hash", b"hash", "salt", b"salt", "username", b"username"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___mobile_authenticate: _TypeAlias = mobile_authenticate  # noqa: Y015
