# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: MobileAuthenticate.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'MobileAuthenticate.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18MobileAuthenticate.proto\x12\x13\x63om.levven.protobuf\"\x82\x01\n\x13mobile_authenticate\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x0c\n\x04salt\x18\x02 \x01(\t\x12\x0c\n\x04hash\x18\x03 \x01(\t\x12=\n\x0b\x61uth_status\x18\x04 \x01(\x0e\x32(.com.levven.protobuf.AUTHENTICATE_STATUS*I\n\x13\x41UTHENTICATE_STATUS\x12\x18\n\x14\x41UTHENTICATE_SUCCESS\x10\x00\x12\x18\n\x14\x41UTHENTICATE_FAILURE\x10\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'MobileAuthenticate_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUTHENTICATE_STATUS']._serialized_start=182
  _globals['_AUTHENTICATE_STATUS']._serialized_end=255
  _globals['_MOBILE_AUTHENTICATE']._serialized_start=50
  _globals['_MOBILE_AUTHENTICATE']._serialized_end=180
# @@protoc_insertion_point(module_scope)
