"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _REGISTRATION_STATUS:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _REGISTRATION_STATUSEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_REGISTRATION_STATUS.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    REGISTRATION_SUCCESS: _REGISTRATION_STATUS.ValueType  # 0
    REGISTRATION_FAILURE: _REGISTRATION_STATUS.ValueType  # 1

class REGISTRATION_STATUS(_REGISTRATION_STATUS, metaclass=_REGISTRATION_STATUSEnumTypeWrapper): ...

REGISTRATION_SUCCESS: REGISTRATION_STATUS.ValueType  # 0
REGISTRATION_FAILURE: REGISTRATION_STATUS.ValueType  # 1
Global___REGISTRATION_STATUS: _TypeAlias = REGISTRATION_STATUS  # noqa: Y015

@_typing.final
class mobile_spa_registration(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REGISTRATION_CODE_FIELD_NUMBER: _builtins.int
    SERIAL_NUMBER_FIELD_NUMBER: _builtins.int
    SPA_NICKNAME_FIELD_NUMBER: _builtins.int
    REG_STATUS_FIELD_NUMBER: _builtins.int
    registration_code: _builtins.str
    serial_number: _builtins.str
    spa_nickname: _builtins.str
    reg_status: Global___REGISTRATION_STATUS.ValueType
    def __init__(
        self,
        *,
        registration_code: _builtins.str | None = ...,
        serial_number: _builtins.str | None = ...,
        spa_nickname: _builtins.str | None = ...,
        reg_status: Global___REGISTRATION_STATUS.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["reg_status", b"reg_status", "registration_code", b"registration_code", "serial_number", b"serial_number", "spa_nickname", b"spa_nickname"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["reg_status", b"reg_status", "registration_code", b"registration_code", "serial_number", b"serial_number", "spa_nickname", b"spa_nickname"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___mobile_spa_registration: _TypeAlias = mobile_spa_registration  # noqa: Y015
