"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _PHASE:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PHASEEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PHASE.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    TRUE_THREE: _PHASE.ValueType  # 0
    SINGLE: _PHASE.ValueType  # 1
    TWO: _PHASE.ValueType  # 2
    THREE: _PHASE.ValueType  # 3

class PHASE(_PHASE, metaclass=_PHASEEnumTypeWrapper): ...

TRUE_THREE: PHASE.ValueType  # 0
SINGLE: PHASE.ValueType  # 1
TWO: PHASE.ValueType  # 2
THREE: PHASE.ValueType  # 3
Global___PHASE: _TypeAlias = PHASE  # noqa: Y015

@_typing.final
class spa_configuration(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PUMP_1_FIELD_NUMBER: _builtins.int
    PUMP_2_FIELD_NUMBER: _builtins.int
    PUMP_3_FIELD_NUMBER: _builtins.int
    PUMP_4_FIELD_NUMBER: _builtins.int
    PUMP_5_FIELD_NUMBER: _builtins.int
    BLOWER_1_FIELD_NUMBER: _builtins.int
    BLOWER_2_FIELD_NUMBER: _builtins.int
    LIGHTS_FIELD_NUMBER: _builtins.int
    STEREO_FIELD_NUMBER: _builtins.int
    HEATER_1_FIELD_NUMBER: _builtins.int
    HEATER_2_FIELD_NUMBER: _builtins.int
    FILTER_FIELD_NUMBER: _builtins.int
    ONZEN_FIELD_NUMBER: _builtins.int
    OZONE_PEAK_1_FIELD_NUMBER: _builtins.int
    OZONE_PEAK_2_FIELD_NUMBER: _builtins.int
    EXHAUST_FAN_FIELD_NUMBER: _builtins.int
    POWERLINES_FIELD_NUMBER: _builtins.int
    BREAKER_SIZE_FIELD_NUMBER: _builtins.int
    SMART_ONZEN_FIELD_NUMBER: _builtins.int
    FOGGER_FIELD_NUMBER: _builtins.int
    pump_1: _builtins.bool
    pump_2: _builtins.bool
    pump_3: _builtins.bool
    pump_4: _builtins.bool
    pump_5: _builtins.bool
    blower_1: _builtins.bool
    blower_2: _builtins.bool
    lights: _builtins.bool
    stereo: _builtins.bool
    heater_1: _builtins.bool
    heater_2: _builtins.bool
    filter: _builtins.bool
    onzen: _builtins.bool
    ozone_peak_1: _builtins.bool
    ozone_peak_2: _builtins.bool
    exhaust_fan: _builtins.bool
    powerlines: Global___PHASE.ValueType
    breaker_size: _builtins.int
    smart_onzen: _builtins.int
    fogger: _builtins.bool
    def __init__(
        self,
        *,
        pump_1: _builtins.bool | None = ...,
        pump_2: _builtins.bool | None = ...,
        pump_3: _builtins.bool | None = ...,
        pump_4: _builtins.bool | None = ...,
        pump_5: _builtins.bool | None = ...,
        blower_1: _builtins.bool | None = ...,
        blower_2: _builtins.bool | None = ...,
        lights: _builtins.bool | None = ...,
        stereo: _builtins.bool | None = ...,
        heater_1: _builtins.bool | None = ...,
        heater_2: _builtins.bool | None = ...,
        filter: _builtins.bool | None = ...,
        onzen: _builtins.bool | None = ...,
        ozone_peak_1: _builtins.bool | None = ...,
        ozone_peak_2: _builtins.bool | None = ...,
        exhaust_fan: _builtins.bool | None = ...,
        powerlines: Global___PHASE.ValueType | None = ...,
        breaker_size: _builtins.int | None = ...,
        smart_onzen: _builtins.int | None = ...,
        fogger: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["blower_1", b"blower_1", "blower_2", b"blower_2", "breaker_size", b"breaker_size", "exhaust_fan", b"exhaust_fan", "filter", b"filter", "fogger", b"fogger", "heater_1", b"heater_1", "heater_2", b"heater_2", "lights", b"lights", "onzen", b"onzen", "ozone_peak_1", b"ozone_peak_1", "ozone_peak_2", b"ozone_peak_2", "powerlines", b"powerlines", "pump_1", b"pump_1", "pump_2", b"pump_2", "pump_3", b"pump_3", "pump_4", b"pump_4", "pump_5", b"pump_5", "smart_onzen", b"smart_onzen", "stereo", b"stereo"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blower_1", b"blower_1", "blower_2", b"blower_2", "breaker_size", b"breaker_size", "exhaust_fan", b"exhaust_fan", "filter", b"filter", "fogger", b"fogger", "heater_1", b"heater_1", "heater_2", b"heater_2", "lights", b"lights", "onzen", b"onzen", "ozone_peak_1", b"ozone_peak_1", "ozone_peak_2", b"ozone_peak_2", "powerlines", b"powerlines", "pump_1", b"pump_1", "pump_2", b"pump_2", "pump_3", b"pump_3", "pump_4", b"pump_4", "pump_5", b"pump_5", "smart_onzen", b"smart_onzen", "stereo", b"stereo"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___spa_configuration: _TypeAlias = spa_configuration  # noqa: Y015
