# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spa_configuration.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'spa_configuration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17spa_configuration.proto\x12\x1bSpaServer.protobuf.ColdFire\"\x9e\x03\n\x11spa_configuration\x12\x0e\n\x06pump_1\x18\x01 \x01(\x08\x12\x0e\n\x06pump_2\x18\x02 \x01(\x08\x12\x0e\n\x06pump_3\x18\x03 \x01(\x08\x12\x0e\n\x06pump_4\x18\x04 \x01(\x08\x12\x0e\n\x06pump_5\x18\x05 \x01(\x08\x12\x10\n\x08\x62lower_1\x18\x06 \x01(\x08\x12\x10\n\x08\x62lower_2\x18\x07 \x01(\x08\x12\x0e\n\x06lights\x18\x08 \x01(\x08\x12\x0e\n\x06stereo\x18\t \x01(\x08\x12\x10\n\x08heater_1\x18\n \x01(\x08\x12\x10\n\x08heater_2\x18\x0b \x01(\x08\x12\x0e\n\x06\x66ilter\x18\x0c \x01(\x08\x12\r\n\x05onzen\x18\r \x01(\x08\x12\x14\n\x0cozone_peak_1\x18\x0e \x01(\x08\x12\x14\n\x0cozone_peak_2\x18\x0f \x01(\x08\x12\x13\n\x0b\x65xhaust_fan\x18\x10 \x01(\x08\x12\x36\n\npowerlines\x18\x11 \x01(\x0e\x32\".SpaServer.protobuf.ColdFire.PHASE\x12\x14\n\x0c\x62reaker_size\x18\x12 \x01(\x05\x12\x13\n\x0bsmart_onzen\x18\x13 \x01(\x05\x12\x0e\n\x06\x66ogger\x18\x14 \x01(\x08*7\n\x05PHASE\x12\x0e\n\nTRUE_THREE\x10\x00\x12\n\n\x06SINGLE\x10\x01\x12\x07\n\x03TWO\x10\x02\x12\t\n\x05THREE\x10\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spa_configuration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PHASE']._serialized_start=473
  _globals['_PHASE']._serialized_end=528
  _globals['_SPA_CONFIGURATION']._serialized_start=57
  _globals['_SPA_CONFIGURATION']._serialized_end=471
# @@protoc_insertion_point(module_scope)
