# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: spa_settings.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'spa_settings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12spa_settings.proto\x12\x1c\x63om.levven.protobuf.coldfire\"\xc2\x05\n\x0cspa_settings\x12 \n\x18max_filtration_frequency\x18\x01 \x01(\x05\x12 \n\x18min_filtration_frequency\x18\x02 \x01(\x05\x12\x1c\n\x14\x66iltration_frequency\x18\x03 \x01(\x05\x12\x1f\n\x17max_filtration_duration\x18\x04 \x01(\x05\x12\x1f\n\x17min_filtration_duration\x18\x05 \x01(\x05\x12\x1b\n\x13\x66iltration_duration\x18\x06 \x01(\x05\x12\x17\n\x0fmax_onzen_hours\x18\x07 \x01(\x05\x12\x17\n\x0fmin_onzen_hours\x18\x08 \x01(\x05\x12\x13\n\x0bonzen_hours\x18\t \x01(\x05\x12\x18\n\x10max_onzen_cycles\x18\n \x01(\x05\x12\x18\n\x10min_onzen_cycles\x18\x0b \x01(\x05\x12\x14\n\x0conzen_cycles\x18\x0c \x01(\x05\x12\x17\n\x0fmax_ozone_hours\x18\r \x01(\x05\x12\x17\n\x0fmin_ozone_hours\x18\x0e \x01(\x05\x12\x13\n\x0bozone_hours\x18\x0f \x01(\x05\x12\x18\n\x10max_ozone_cycles\x18\x10 \x01(\x05\x12\x18\n\x10min_ozone_cycles\x18\x11 \x01(\x05\x12\x14\n\x0cozone_cycles\x18\x12 \x01(\x05\x12\x19\n\x11\x66ilter_suspension\x18\x13 \x01(\x08\x12\x1d\n\x15\x66lash_lights_on_error\x18\x14 \x01(\x08\x12\x1a\n\x12temperature_offset\x18\x15 \x01(\x05\x12\x16\n\x0esauna_duration\x18\x16 \x01(\x05\x12\x17\n\x0fmin_temperature\x18\x17 \x01(\x05\x12\x17\n\x0fmax_temperature\x18\x18 \x01(\x05\x12\x19\n\x11\x66iltration_offset\x18\x19 \x01(\x05\x12\x14\n\x0cspaboy_hours\x18\x1a \x01(\x05')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'spa_settings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPA_SETTINGS']._serialized_start=53
  _globals['_SPA_SETTINGS']._serialized_end=759
# @@protoc_insertion_point(module_scope)
