"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _PUMP_STATUS:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PUMP_STATUSEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PUMP_STATUS.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    OFF: _PUMP_STATUS.ValueType  # 0
    LOW: _PUMP_STATUS.ValueType  # 1
    HIGH: _PUMP_STATUS.ValueType  # 2

class PUMP_STATUS(_PUMP_STATUS, metaclass=_PUMP_STATUSEnumTypeWrapper): ...

OFF: PUMP_STATUS.ValueType  # 0
LOW: PUMP_STATUS.ValueType  # 1
HIGH: PUMP_STATUS.ValueType  # 2
Global___PUMP_STATUS: _TypeAlias = PUMP_STATUS  # noqa: Y015

class _HEATER_STATUS:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _HEATER_STATUSEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_HEATER_STATUS.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    IDLE: _HEATER_STATUS.ValueType  # 0
    WARMUP: _HEATER_STATUS.ValueType  # 1
    HEATING: _HEATER_STATUS.ValueType  # 2
    COOLDOWN: _HEATER_STATUS.ValueType  # 3

class HEATER_STATUS(_HEATER_STATUS, metaclass=_HEATER_STATUSEnumTypeWrapper): ...

IDLE: HEATER_STATUS.ValueType  # 0
WARMUP: HEATER_STATUS.ValueType  # 1
HEATING: HEATER_STATUS.ValueType  # 2
COOLDOWN: HEATER_STATUS.ValueType  # 3
Global___HEATER_STATUS: _TypeAlias = HEATER_STATUS  # noqa: Y015

class _FILTER_STATUS:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _FILTER_STATUSEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_FILTER_STATUS.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    FILTER_IDLE: _FILTER_STATUS.ValueType  # 0
    FILTER_PURGE: _FILTER_STATUS.ValueType  # 1
    FILTER_FILTERING: _FILTER_STATUS.ValueType  # 2
    FILTER_SUSPENDED: _FILTER_STATUS.ValueType  # 3
    FILTER_OVERTEMPERATURE: _FILTER_STATUS.ValueType  # 4
    FILTER_RESUMING: _FILTER_STATUS.ValueType  # 5
    FILTER_BOOST: _FILTER_STATUS.ValueType  # 6
    FILTER_SANITIZE: _FILTER_STATUS.ValueType  # 7

class FILTER_STATUS(_FILTER_STATUS, metaclass=_FILTER_STATUSEnumTypeWrapper): ...

FILTER_IDLE: FILTER_STATUS.ValueType  # 0
FILTER_PURGE: FILTER_STATUS.ValueType  # 1
FILTER_FILTERING: FILTER_STATUS.ValueType  # 2
FILTER_SUSPENDED: FILTER_STATUS.ValueType  # 3
FILTER_OVERTEMPERATURE: FILTER_STATUS.ValueType  # 4
FILTER_RESUMING: FILTER_STATUS.ValueType  # 5
FILTER_BOOST: FILTER_STATUS.ValueType  # 6
FILTER_SANITIZE: FILTER_STATUS.ValueType  # 7
Global___FILTER_STATUS: _TypeAlias = FILTER_STATUS  # noqa: Y015

class _OZONE_STATUS:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _OZONE_STATUSEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_OZONE_STATUS.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    OZONE_IDLE: _OZONE_STATUS.ValueType  # 0
    OZONE_ACTIVE: _OZONE_STATUS.ValueType  # 1
    OZONE_SUSPENDED: _OZONE_STATUS.ValueType  # 2

class OZONE_STATUS(_OZONE_STATUS, metaclass=_OZONE_STATUSEnumTypeWrapper): ...

OZONE_IDLE: OZONE_STATUS.ValueType  # 0
OZONE_ACTIVE: OZONE_STATUS.ValueType  # 1
OZONE_SUSPENDED: OZONE_STATUS.ValueType  # 2
Global___OZONE_STATUS: _TypeAlias = OZONE_STATUS  # noqa: Y015

class _SAUNA_STATUS:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _SAUNA_STATUSEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_SAUNA_STATUS.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    SAUNA_STATUS_IDLE: _SAUNA_STATUS.ValueType  # 0
    SAUNA_STATUS_NORMAL: _SAUNA_STATUS.ValueType  # 1
    SAUNA_STATUS_PRESET_A: _SAUNA_STATUS.ValueType  # 2
    SAUNA_STATUS_PRESET_B: _SAUNA_STATUS.ValueType  # 3
    SAUNA_STATUS_PRESET_C: _SAUNA_STATUS.ValueType  # 4

class SAUNA_STATUS(_SAUNA_STATUS, metaclass=_SAUNA_STATUSEnumTypeWrapper): ...

SAUNA_STATUS_IDLE: SAUNA_STATUS.ValueType  # 0
SAUNA_STATUS_NORMAL: SAUNA_STATUS.ValueType  # 1
SAUNA_STATUS_PRESET_A: SAUNA_STATUS.ValueType  # 2
SAUNA_STATUS_PRESET_B: SAUNA_STATUS.ValueType  # 3
SAUNA_STATUS_PRESET_C: SAUNA_STATUS.ValueType  # 4
Global___SAUNA_STATUS: _TypeAlias = SAUNA_STATUS  # noqa: Y015

@_typing.final
class spa_live(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TEMPERATURE_FAHRENHEIT_FIELD_NUMBER: _builtins.int
    TEMPERATURE_SETPOINT_FAHRENHEIT_FIELD_NUMBER: _builtins.int
    PUMP_1_FIELD_NUMBER: _builtins.int
    PUMP_2_FIELD_NUMBER: _builtins.int
    PUMP_3_FIELD_NUMBER: _builtins.int
    PUMP_4_FIELD_NUMBER: _builtins.int
    PUMP_5_FIELD_NUMBER: _builtins.int
    BLOWER_1_FIELD_NUMBER: _builtins.int
    BLOWER_2_FIELD_NUMBER: _builtins.int
    LIGHTS_FIELD_NUMBER: _builtins.int
    STEREO_FIELD_NUMBER: _builtins.int
    HEATER_1_FIELD_NUMBER: _builtins.int
    HEATER_2_FIELD_NUMBER: _builtins.int
    FILTER_FIELD_NUMBER: _builtins.int
    ONZEN_FIELD_NUMBER: _builtins.int
    OZONE_FIELD_NUMBER: _builtins.int
    EXHAUST_FAN_FIELD_NUMBER: _builtins.int
    SAUNA_FIELD_NUMBER: _builtins.int
    HEATER_ADC_FIELD_NUMBER: _builtins.int
    SAUNA_TIME_REMAINING_FIELD_NUMBER: _builtins.int
    ECONOMY_FIELD_NUMBER: _builtins.int
    CURRENT_ADC_FIELD_NUMBER: _builtins.int
    ALL_ON_FIELD_NUMBER: _builtins.int
    FOGGER_FIELD_NUMBER: _builtins.int
    temperature_fahrenheit: _builtins.int
    temperature_setpoint_fahrenheit: _builtins.int
    pump_1: Global___PUMP_STATUS.ValueType
    pump_2: Global___PUMP_STATUS.ValueType
    pump_3: Global___PUMP_STATUS.ValueType
    pump_4: Global___PUMP_STATUS.ValueType
    pump_5: Global___PUMP_STATUS.ValueType
    blower_1: Global___PUMP_STATUS.ValueType
    blower_2: Global___PUMP_STATUS.ValueType
    lights: _builtins.bool
    stereo: _builtins.bool
    heater_1: Global___HEATER_STATUS.ValueType
    heater_2: Global___HEATER_STATUS.ValueType
    filter: Global___FILTER_STATUS.ValueType
    onzen: _builtins.bool
    ozone: Global___OZONE_STATUS.ValueType
    exhaust_fan: _builtins.bool
    sauna: Global___SAUNA_STATUS.ValueType
    heater_adc: _builtins.int
    sauna_time_remaining: _builtins.int
    economy: _builtins.bool
    current_adc: _builtins.int
    all_on: _builtins.bool
    fogger: _builtins.bool
    def __init__(
        self,
        *,
        temperature_fahrenheit: _builtins.int | None = ...,
        temperature_setpoint_fahrenheit: _builtins.int | None = ...,
        pump_1: Global___PUMP_STATUS.ValueType | None = ...,
        pump_2: Global___PUMP_STATUS.ValueType | None = ...,
        pump_3: Global___PUMP_STATUS.ValueType | None = ...,
        pump_4: Global___PUMP_STATUS.ValueType | None = ...,
        pump_5: Global___PUMP_STATUS.ValueType | None = ...,
        blower_1: Global___PUMP_STATUS.ValueType | None = ...,
        blower_2: Global___PUMP_STATUS.ValueType | None = ...,
        lights: _builtins.bool | None = ...,
        stereo: _builtins.bool | None = ...,
        heater_1: Global___HEATER_STATUS.ValueType | None = ...,
        heater_2: Global___HEATER_STATUS.ValueType | None = ...,
        filter: Global___FILTER_STATUS.ValueType | None = ...,
        onzen: _builtins.bool | None = ...,
        ozone: Global___OZONE_STATUS.ValueType | None = ...,
        exhaust_fan: _builtins.bool | None = ...,
        sauna: Global___SAUNA_STATUS.ValueType | None = ...,
        heater_adc: _builtins.int | None = ...,
        sauna_time_remaining: _builtins.int | None = ...,
        economy: _builtins.bool | None = ...,
        current_adc: _builtins.int | None = ...,
        all_on: _builtins.bool | None = ...,
        fogger: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["all_on", b"all_on", "blower_1", b"blower_1", "blower_2", b"blower_2", "current_adc", b"current_adc", "economy", b"economy", "exhaust_fan", b"exhaust_fan", "filter", b"filter", "fogger", b"fogger", "heater_1", b"heater_1", "heater_2", b"heater_2", "heater_adc", b"heater_adc", "lights", b"lights", "onzen", b"onzen", "ozone", b"ozone", "pump_1", b"pump_1", "pump_2", b"pump_2", "pump_3", b"pump_3", "pump_4", b"pump_4", "pump_5", b"pump_5", "sauna", b"sauna", "sauna_time_remaining", b"sauna_time_remaining", "stereo", b"stereo", "temperature_fahrenheit", b"temperature_fahrenheit", "temperature_setpoint_fahrenheit", b"temperature_setpoint_fahrenheit"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["all_on", b"all_on", "blower_1", b"blower_1", "blower_2", b"blower_2", "current_adc", b"current_adc", "economy", b"economy", "exhaust_fan", b"exhaust_fan", "filter", b"filter", "fogger", b"fogger", "heater_1", b"heater_1", "heater_2", b"heater_2", "heater_adc", b"heater_adc", "lights", b"lights", "onzen", b"onzen", "ozone", b"ozone", "pump_1", b"pump_1", "pump_2", b"pump_2", "pump_3", b"pump_3", "pump_4", b"pump_4", "pump_5", b"pump_5", "sauna", b"sauna", "sauna_time_remaining", b"sauna_time_remaining", "stereo", b"stereo", "temperature_fahrenheit", b"temperature_fahrenheit", "temperature_setpoint_fahrenheit", b"temperature_setpoint_fahrenheit"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___spa_live: _TypeAlias = spa_live  # noqa: Y015
