# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SpaCommand.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'SpaCommand.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10SpaCommand.proto\x12\x03spa\"\x9c\x05\n\x0bspa_command\x12+\n#set_temperature_setpoint_fahrenheit\x18\x01 \x01(\x05\x12(\n\nset_pump_1\x18\x02 \x01(\x0e\x32\x14.spa.SET_PUMP_STATUS\x12(\n\nset_pump_2\x18\x03 \x01(\x0e\x32\x14.spa.SET_PUMP_STATUS\x12(\n\nset_pump_3\x18\x04 \x01(\x0e\x32\x14.spa.SET_PUMP_STATUS\x12(\n\nset_pump_4\x18\x05 \x01(\x0e\x32\x14.spa.SET_PUMP_STATUS\x12(\n\nset_pump_5\x18\x06 \x01(\x0e\x32\x14.spa.SET_PUMP_STATUS\x12*\n\x0cset_blower_1\x18\x07 \x01(\x0e\x32\x14.spa.SET_PUMP_STATUS\x12*\n\x0cset_blower_2\x18\x08 \x01(\x0e\x32\x14.spa.SET_PUMP_STATUS\x12\x12\n\nset_lights\x18\t \x01(\x08\x12\x12\n\nset_stereo\x18\n \x01(\x08\x12\x12\n\nset_filter\x18\x0b \x01(\x08\x12\x11\n\tset_onzen\x18\x0c \x01(\x08\x12\x11\n\tset_ozone\x18\r \x01(\x08\x12\x17\n\x0fset_exhaust_fan\x18\x0e \x01(\x08\x12-\n\x0fset_sauna_state\x18\x0f \x01(\x0e\x32\x14.spa.SET_SAUNA_STATE\x12\x1b\n\x13set_sauna_time_left\x18\x10 \x01(\x05\x12\x0e\n\x06\x61ll_on\x18\x11 \x01(\x08\x12\x12\n\nset_fogger\x18\x12 \x01(\x08\x12\x14\n\x0cspaboy_boost\x18\x13 \x01(\x08\x12\x19\n\x11set_orp_level_low\x18\x32 \x01(\x05\x12\x1a\n\x12set_orp_level_high\x18\x33 \x01(\x05*-\n\x0fSET_PUMP_STATUS\x12\x07\n\x03OFF\x10\x00\x12\x07\n\x03LOW\x10\x01\x12\x08\n\x04HIGH\x10\x02*P\n\x0fSET_SAUNA_STATE\x12\x08\n\x04IDLE\x10\x00\x12\t\n\x05TIMER\x10\x01\x12\x0c\n\x08PRESET_A\x10\x02\x12\x0c\n\x08PRESET_B\x10\x03\x12\x0c\n\x08PRESET_C\x10\x04')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SpaCommand_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SET_PUMP_STATUS']._serialized_start=696
  _globals['_SET_PUMP_STATUS']._serialized_end=741
  _globals['_SET_SAUNA_STATE']._serialized_start=743
  _globals['_SET_SAUNA_STATE']._serialized_end=823
  _globals['_SPA_COMMAND']._serialized_start=26
  _globals['_SPA_COMMAND']._serialized_end=694
# @@protoc_insertion_point(module_scope)
