# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SpaError.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'SpaError.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eSpaError.proto\x12\x1c\x63om.levven.protobuf.coldfire\"\x83\x02\n\tspa_error\x12\x0f\n\x07no_flow\x18\x01 \x01(\x08\x12\x13\n\x0b\x66low_switch\x18\x02 \x01(\x08\x12\x1f\n\x17heater_over_temperature\x18\x03 \x01(\x08\x12\x1c\n\x14spa_over_temperature\x18\x04 \x01(\x08\x12\x1d\n\x15spa_temperature_probe\x18\x05 \x01(\x08\x12\x16\n\x0espa_high_limit\x18\x06 \x01(\x08\x12\x0e\n\x06\x65\x65prom\x18\x07 \x01(\x08\x12\x16\n\x0e\x66reeze_protect\x18\x08 \x01(\x08\x12\x0f\n\x07ph_high\x18\t \x01(\x08\x12!\n\x19heater_probe_disconnected\x18\n \x01(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SpaError_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPA_ERROR']._serialized_start=49
  _globals['_SPA_ERROR']._serialized_end=308
# @@protoc_insertion_point(module_scope)
