"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class spa_error(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NO_FLOW_FIELD_NUMBER: _builtins.int
    FLOW_SWITCH_FIELD_NUMBER: _builtins.int
    HEATER_OVER_TEMPERATURE_FIELD_NUMBER: _builtins.int
    SPA_OVER_TEMPERATURE_FIELD_NUMBER: _builtins.int
    SPA_TEMPERATURE_PROBE_FIELD_NUMBER: _builtins.int
    SPA_HIGH_LIMIT_FIELD_NUMBER: _builtins.int
    EEPROM_FIELD_NUMBER: _builtins.int
    FREEZE_PROTECT_FIELD_NUMBER: _builtins.int
    PH_HIGH_FIELD_NUMBER: _builtins.int
    HEATER_PROBE_DISCONNECTED_FIELD_NUMBER: _builtins.int
    no_flow: _builtins.bool
    flow_switch: _builtins.bool
    heater_over_temperature: _builtins.bool
    spa_over_temperature: _builtins.bool
    spa_temperature_probe: _builtins.bool
    spa_high_limit: _builtins.bool
    eeprom: _builtins.bool
    freeze_protect: _builtins.bool
    ph_high: _builtins.bool
    heater_probe_disconnected: _builtins.bool
    def __init__(
        self,
        *,
        no_flow: _builtins.bool | None = ...,
        flow_switch: _builtins.bool | None = ...,
        heater_over_temperature: _builtins.bool | None = ...,
        spa_over_temperature: _builtins.bool | None = ...,
        spa_temperature_probe: _builtins.bool | None = ...,
        spa_high_limit: _builtins.bool | None = ...,
        eeprom: _builtins.bool | None = ...,
        freeze_protect: _builtins.bool | None = ...,
        ph_high: _builtins.bool | None = ...,
        heater_probe_disconnected: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["eeprom", b"eeprom", "flow_switch", b"flow_switch", "freeze_protect", b"freeze_protect", "heater_over_temperature", b"heater_over_temperature", "heater_probe_disconnected", b"heater_probe_disconnected", "no_flow", b"no_flow", "ph_high", b"ph_high", "spa_high_limit", b"spa_high_limit", "spa_over_temperature", b"spa_over_temperature", "spa_temperature_probe", b"spa_temperature_probe"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["eeprom", b"eeprom", "flow_switch", b"flow_switch", "freeze_protect", b"freeze_protect", "heater_over_temperature", b"heater_over_temperature", "heater_probe_disconnected", b"heater_probe_disconnected", "no_flow", b"no_flow", "ph_high", b"ph_high", "spa_high_limit", b"spa_high_limit", "spa_over_temperature", b"spa_over_temperature", "spa_temperature_probe", b"spa_temperature_probe"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___spa_error: _TypeAlias = spa_error  # noqa: Y015
