# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SpaPeak.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'SpaPeak.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rSpaPeak.proto\x12\x1c\x63om.levven.protobuf.coldfire\"\xe7\x03\n\x08spa_peak\x12\x0f\n\x07PeakNum\x18\x01 \x01(\x05\x12\x12\n\nPeakStart1\x18\x02 \x01(\x05\x12\x10\n\x08PeakEnd1\x18\x03 \x01(\x05\x12\x12\n\nPeakStart2\x18\x04 \x01(\x05\x12\x10\n\x08PeakEnd2\x18\x05 \x01(\x05\x12\x12\n\nMidPeakNum\x18\x06 \x01(\x05\x12\x15\n\rMidPeakStart1\x18\x07 \x01(\x05\x12\x13\n\x0bMidPeakEnd1\x18\x08 \x01(\x05\x12\x15\n\rMidPeakStart2\x18\t \x01(\x05\x12\x13\n\x0bMidPeakEnd2\x18\n \x01(\x05\x12\x14\n\x0cOffPeakStart\x18\x0b \x01(\x05\x12\x12\n\nOffPeakEnd\x18\x0c \x01(\x05\x12\x0e\n\x06Offset\x18\r \x01(\x05\x12\x12\n\nPeakHeater\x18\x0e \x01(\x08\x12\x12\n\nPeakFilter\x18\x0f \x01(\x08\x12\x11\n\tPeakOzone\x18\x10 \x01(\x08\x12\x15\n\rMidPeakHeater\x18\x11 \x01(\x08\x12\x15\n\rMidPeakFilter\x18\x12 \x01(\x08\x12\x14\n\x0cMidPeakOzone\x18\x13 \x01(\x08\x12\x0b\n\x03Sat\x18\x14 \x01(\x08\x12\x0b\n\x03Sun\x18\x15 \x01(\x08\x12\x0b\n\x03Mon\x18\x16 \x01(\x08\x12\x0b\n\x03Tue\x18\x17 \x01(\x08\x12\x0b\n\x03Wed\x18\x18 \x01(\x08\x12\x0b\n\x03Thu\x18\x19 \x01(\x08\x12\x0b\n\x03\x46ri\x18\x1a \x01(\x08')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SpaPeak_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SPA_PEAK']._serialized_start=48
  _globals['_SPA_PEAK']._serialized_end=535
# @@protoc_insertion_point(module_scope)
