"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class spa_peak(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    PEAKNUM_FIELD_NUMBER: _builtins.int
    PEAKSTART1_FIELD_NUMBER: _builtins.int
    PEAKEND1_FIELD_NUMBER: _builtins.int
    PEAKSTART2_FIELD_NUMBER: _builtins.int
    PEAKEND2_FIELD_NUMBER: _builtins.int
    MIDPEAKNUM_FIELD_NUMBER: _builtins.int
    MIDPEAKSTART1_FIELD_NUMBER: _builtins.int
    MIDPEAKEND1_FIELD_NUMBER: _builtins.int
    MIDPEAKSTART2_FIELD_NUMBER: _builtins.int
    MIDPEAKEND2_FIELD_NUMBER: _builtins.int
    OFFPEAKSTART_FIELD_NUMBER: _builtins.int
    OFFPEAKEND_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    PEAKHEATER_FIELD_NUMBER: _builtins.int
    PEAKFILTER_FIELD_NUMBER: _builtins.int
    PEAKOZONE_FIELD_NUMBER: _builtins.int
    MIDPEAKHEATER_FIELD_NUMBER: _builtins.int
    MIDPEAKFILTER_FIELD_NUMBER: _builtins.int
    MIDPEAKOZONE_FIELD_NUMBER: _builtins.int
    SAT_FIELD_NUMBER: _builtins.int
    SUN_FIELD_NUMBER: _builtins.int
    MON_FIELD_NUMBER: _builtins.int
    TUE_FIELD_NUMBER: _builtins.int
    WED_FIELD_NUMBER: _builtins.int
    THU_FIELD_NUMBER: _builtins.int
    FRI_FIELD_NUMBER: _builtins.int
    PeakNum: _builtins.int
    PeakStart1: _builtins.int
    PeakEnd1: _builtins.int
    PeakStart2: _builtins.int
    PeakEnd2: _builtins.int
    MidPeakNum: _builtins.int
    MidPeakStart1: _builtins.int
    MidPeakEnd1: _builtins.int
    MidPeakStart2: _builtins.int
    MidPeakEnd2: _builtins.int
    OffPeakStart: _builtins.int
    OffPeakEnd: _builtins.int
    Offset: _builtins.int
    PeakHeater: _builtins.bool
    PeakFilter: _builtins.bool
    PeakOzone: _builtins.bool
    MidPeakHeater: _builtins.bool
    MidPeakFilter: _builtins.bool
    MidPeakOzone: _builtins.bool
    Sat: _builtins.bool
    Sun: _builtins.bool
    Mon: _builtins.bool
    Tue: _builtins.bool
    Wed: _builtins.bool
    Thu: _builtins.bool
    Fri: _builtins.bool
    def __init__(
        self,
        *,
        PeakNum: _builtins.int | None = ...,
        PeakStart1: _builtins.int | None = ...,
        PeakEnd1: _builtins.int | None = ...,
        PeakStart2: _builtins.int | None = ...,
        PeakEnd2: _builtins.int | None = ...,
        MidPeakNum: _builtins.int | None = ...,
        MidPeakStart1: _builtins.int | None = ...,
        MidPeakEnd1: _builtins.int | None = ...,
        MidPeakStart2: _builtins.int | None = ...,
        MidPeakEnd2: _builtins.int | None = ...,
        OffPeakStart: _builtins.int | None = ...,
        OffPeakEnd: _builtins.int | None = ...,
        Offset: _builtins.int | None = ...,
        PeakHeater: _builtins.bool | None = ...,
        PeakFilter: _builtins.bool | None = ...,
        PeakOzone: _builtins.bool | None = ...,
        MidPeakHeater: _builtins.bool | None = ...,
        MidPeakFilter: _builtins.bool | None = ...,
        MidPeakOzone: _builtins.bool | None = ...,
        Sat: _builtins.bool | None = ...,
        Sun: _builtins.bool | None = ...,
        Mon: _builtins.bool | None = ...,
        Tue: _builtins.bool | None = ...,
        Wed: _builtins.bool | None = ...,
        Thu: _builtins.bool | None = ...,
        Fri: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["Fri", b"Fri", "MidPeakEnd1", b"MidPeakEnd1", "MidPeakEnd2", b"MidPeakEnd2", "MidPeakFilter", b"MidPeakFilter", "MidPeakHeater", b"MidPeakHeater", "MidPeakNum", b"MidPeakNum", "MidPeakOzone", b"MidPeakOzone", "MidPeakStart1", b"MidPeakStart1", "MidPeakStart2", b"MidPeakStart2", "Mon", b"Mon", "OffPeakEnd", b"OffPeakEnd", "OffPeakStart", b"OffPeakStart", "Offset", b"Offset", "PeakEnd1", b"PeakEnd1", "PeakEnd2", b"PeakEnd2", "PeakFilter", b"PeakFilter", "PeakHeater", b"PeakHeater", "PeakNum", b"PeakNum", "PeakOzone", b"PeakOzone", "PeakStart1", b"PeakStart1", "PeakStart2", b"PeakStart2", "Sat", b"Sat", "Sun", b"Sun", "Thu", b"Thu", "Tue", b"Tue", "Wed", b"Wed"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["Fri", b"Fri", "MidPeakEnd1", b"MidPeakEnd1", "MidPeakEnd2", b"MidPeakEnd2", "MidPeakFilter", b"MidPeakFilter", "MidPeakHeater", b"MidPeakHeater", "MidPeakNum", b"MidPeakNum", "MidPeakOzone", b"MidPeakOzone", "MidPeakStart1", b"MidPeakStart1", "MidPeakStart2", b"MidPeakStart2", "Mon", b"Mon", "OffPeakEnd", b"OffPeakEnd", "OffPeakStart", b"OffPeakStart", "Offset", b"Offset", "PeakEnd1", b"PeakEnd1", "PeakEnd2", b"PeakEnd2", "PeakFilter", b"PeakFilter", "PeakHeater", b"PeakHeater", "PeakNum", b"PeakNum", "PeakOzone", b"PeakOzone", "PeakStart1", b"PeakStart1", "PeakStart2", b"PeakStart2", "Sat", b"Sat", "Sun", b"Sun", "Thu", b"Thu", "Tue", b"Tue", "Wed", b"Wed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___spa_peak: _TypeAlias = spa_peak  # noqa: Y015
