# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: SpaRouter.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'SpaRouter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fSpaRouter.proto\x12\x1c\x63om.levven.protobuf.coldfire\"\xa4\x01\n\nspa_router\x12\x0c\n\x04ssid\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12<\n\nencryption\x18\x03 \x01(\x0e\x32(.com.levven.protobuf.coldfire.ENCRYPTION\x12\x38\n\x08protocol\x18\x04 \x01(\x0e\x32&.com.levven.protobuf.coldfire.PROTOCOL*^\n\nENCRYPTION\x12\x13\n\x0f\x45NCRYPTION_NONE\x10\x00\x12\x12\n\x0e\x45NCRYPTION_WEP\x10\x01\x12\x12\n\x0e\x45NCRYPTION_WPA\x10\x02\x12\x13\n\x0f\x45NCRYPTION_WPA2\x10\x03*B\n\x08PROTOCOL\x12\x11\n\rPROTOCOL_NONE\x10\x00\x12\x10\n\x0cPROTOCOL_AES\x10\x01\x12\x11\n\rPROTOCOL_TKIP\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'SpaRouter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ENCRYPTION']._serialized_start=216
  _globals['_ENCRYPTION']._serialized_end=310
  _globals['_PROTOCOL']._serialized_start=312
  _globals['_PROTOCOL']._serialized_end=378
  _globals['_SPA_ROUTER']._serialized_start=50
  _globals['_SPA_ROUTER']._serialized_end=214
# @@protoc_insertion_point(module_scope)
