"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _ENCRYPTION:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _ENCRYPTIONEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_ENCRYPTION.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ENCRYPTION_NONE: _ENCRYPTION.ValueType  # 0
    ENCRYPTION_WEP: _ENCRYPTION.ValueType  # 1
    ENCRYPTION_WPA: _ENCRYPTION.ValueType  # 2
    ENCRYPTION_WPA2: _ENCRYPTION.ValueType  # 3

class ENCRYPTION(_ENCRYPTION, metaclass=_ENCRYPTIONEnumTypeWrapper): ...

ENCRYPTION_NONE: ENCRYPTION.ValueType  # 0
ENCRYPTION_WEP: ENCRYPTION.ValueType  # 1
ENCRYPTION_WPA: ENCRYPTION.ValueType  # 2
ENCRYPTION_WPA2: ENCRYPTION.ValueType  # 3
Global___ENCRYPTION: _TypeAlias = ENCRYPTION  # noqa: Y015

class _PROTOCOL:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _PROTOCOLEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_PROTOCOL.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    PROTOCOL_NONE: _PROTOCOL.ValueType  # 0
    PROTOCOL_AES: _PROTOCOL.ValueType  # 1
    PROTOCOL_TKIP: _PROTOCOL.ValueType  # 2

class PROTOCOL(_PROTOCOL, metaclass=_PROTOCOLEnumTypeWrapper): ...

PROTOCOL_NONE: PROTOCOL.ValueType  # 0
PROTOCOL_AES: PROTOCOL.ValueType  # 1
PROTOCOL_TKIP: PROTOCOL.ValueType  # 2
Global___PROTOCOL: _TypeAlias = PROTOCOL  # noqa: Y015

@_typing.final
class spa_router(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SSID_FIELD_NUMBER: _builtins.int
    PASSWORD_FIELD_NUMBER: _builtins.int
    ENCRYPTION_FIELD_NUMBER: _builtins.int
    PROTOCOL_FIELD_NUMBER: _builtins.int
    ssid: _builtins.str
    password: _builtins.str
    encryption: Global___ENCRYPTION.ValueType
    protocol: Global___PROTOCOL.ValueType
    def __init__(
        self,
        *,
        ssid: _builtins.str | None = ...,
        password: _builtins.str | None = ...,
        encryption: Global___ENCRYPTION.ValueType | None = ...,
        protocol: Global___PROTOCOL.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["encryption", b"encryption", "password", b"password", "protocol", b"protocol", "ssid", b"ssid"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["encryption", b"encryption", "password", b"password", "protocol", b"protocol", "ssid", b"ssid"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___spa_router: _TypeAlias = spa_router  # noqa: Y015
